// Generated by scalus-ts-exporter. DO NOT EDIT.

/**
 * A constructor `val` carrying @TsType narrows BOTH faces: the property and the constructor
 * parameter. Annotated on the parameter here, and via the field meta-target in {@link BothFacesMeta}.
 */
export class BothFaces {
  constructor(kind: "a" | "b");
  readonly kind: "a" | "b";
}

export class BothFacesMeta {
  constructor(kind: "a" | "b");
  readonly kind: "a" | "b";
}

/** A generic exported class with a bounded type parameter. */
export class BoundedBox<A extends object> {
  constructor(value: A);
  readonly value: A;
}

/** Generic exported class. */
export class Box<A> {
  constructor(value: A);
  readonly value: A;
}

/** A callback we invoke: its parameters are values we hand OUT, so they must stay mutable. */
export class Callbacks {
  constructor();
  each(f: (arg0: string[]) => void): void;
}

export interface CfgEntry {
  readonly tags: readonly string[];
}

/** Inherits `kind` and `describe` from {@link Shape} and overrides `sides`. */
export class Circle {
  constructor(radius: number);
  readonly radius: number;
  sides(): number;
  readonly kind: string;
  /** A human-readable description. */
  describe(): string;
}

/** Referenced but not exported: becomes an interface, renamed via @TsName. */
export interface Config {
  /** Nested reference chases transitively. */
  readonly nested?: Inner[];
  readonly flag: boolean;
}

/** An exported js.Object singleton: every public member is exported. */
export const Consts: {
  /** The answer. */
  readonly answer: number;
  negate(x: number): number;
};

export interface DirIn {
  readonly shared: DirShared;
}

export interface DirNested {
  readonly shared: DirShared;
}

export class DirOrder {
  constructor();
  take(a: DirIn): void;
  give(): DirOut;
}

export interface DirOut {
  readonly nested: DirNested;
}

export interface DirShared {
  readonly xs: string[];
}

export class Directional {
  constructor();
  accept(cfg: InputCfg): void;
  produce(): OutputInfo;
}

/**
 * Rich documentation.
 *
 * A link to an exported name stays live: {@link Point}. A Scala-only target degrades to code:
 * `scala.Predef`.
 *
 * @example
 *   ```ts
 *   const d = new Documented();
 *   d.pick("a");
 *   ```
 */
export class Documented {
  constructor();
  /**
   * Picks a value.
   *
   * Accepts one of
   *   - a string
   *   - a number
   *
   * @typeParam A the element type
   * @param a the value to pick
   * @returns the value it was given
   * @throws IllegalArgumentException never, in practice
   */
  pick<A>(a: A): A;
}

/** Referenced but not exported: a generic chased trait. */
export interface GenPair<A, B> {
  readonly first: A;
  readonly second: B;
}

/** Generic types used from member signatures. */
export class Generics {
  constructor();
  /** A generic exported class as a return type. */
  getBox(): Box<string>;
  /** Nested generics. */
  boxes(xs: readonly Box<string>[]): Box<number[]>[];
  /** A generic chased trait, with the type arguments applied. */
  pair(p: GenPair<string, number>): GenPair<number, Box<string>>;
  /** A generic method. */
  pick<A>(a: A, b: A): A;
  /** A generic method with a bounded type parameter. */
  widen<A extends object>(a: A): Box<A>;
}

export interface Inner {
  readonly id: string;
}

/**
 * Only ever passed IN, like EmulatorInitialState: its arrays accept a caller's ReadonlyArray, and
 * that input position propagates to the traits nested inside it.
 */
export interface InputCfg {
  readonly entries: readonly CfgEntry[];
  readonly grid: readonly (readonly number[])[];
}

/** Intersection types. */
export class Intersections {
  constructor();
  /** A user intersection maps to a TypeScript intersection. */
  both(x: Config & Inner): Config & Inner;
  /** js.Object on one side is kept rather than one side being silently picked. */
  withObject(x: object & Inner): object & Inner;
}

/** Every mappable type in one class. */
export class Kitchen {
  constructor();
  prims(a: boolean, b: number, c: number, d: string): void;
  big(x: bigint): bigint;
  arr(xs: readonly string[]): number[][];
  undef(x?: string): number | undefined;
  union(x: bigint | null): Uint8Array | null;
  dict(d: { [key: string]: string }): { [key: string]: number[] };
  promise(): Promise<string>;
  fun(f: (arg0: number) => string): () => void;
  dyn(x: any): any;
  bytes(u: Uint8Array): Uint8Array;
  obj(o: object): object;
  opt(a: number, b?: string, c?: number): void;
  dflt(a: number, b?: string): number;
  readonly ro: number;
  rw: string;
  readonly getter: number;
  overloaded(a: number): number;
  overloaded(a: number, b: string): string;
  credType(): "key" | "script";
  config(c: Config): Config;
}

/**
 * Scala's `@deprecated` must reach the .d.ts as the TSDoc tag: with a message and a version, with
 * a message alone, bare, and never duplicating a `@deprecated` already written by hand.
 * @deprecated Use Point instead (since 1.2.0)
 */
export class Legacy {
  constructor();
  /** @deprecated Use Point.dist (since 1.3.0) */
  distance(): number;
  /** @deprecated No replacement */
  orphan(): number;
  /** @deprecated */
  readonly bare: number;
  /**
   * Still here for now.
   *
   * @deprecated hand-written wording wins over the annotation
   */
  handWritten(): number;
}

/** Exported under a canonical name plus a deprecated alias. */
export class NewName {
  constructor(n: number);
  readonly n: number;
}

/** The doc below belongs to `a` alone; `b` must not inherit it. */
export class OneLiners {
  constructor();
  /** Doc for a. */
  a(): number;
  b(): number;
}

/** Only ever handed BACK, like SubmitResult: its arrays stay mutable. */
export interface OutputInfo {
  readonly notes: string[];
}

/** Non-js.Object class: only annotated members are exported. */
export class Partial {
  constructor(secret: string);
  visible(a: bigint): bigint;
}

/**
 * A point.
 *
 * @param x the x coordinate
 */
export class Point {
  constructor(x: number, y: number);
  readonly x: number;
  readonly y: number;
  /** Distance to {@link Point} `other`. */
  dist(other: Point): number;
}

/**
 * A rectangle.
 *
 * @param width the width in pixels
 */
export class Rect {
  /** Creates a rectangle from its width and height. */
  constructor(width: number, height: number);
  /** The width, measured in pixels. */
  readonly width: number;
  readonly height: number;
}

/** Members exported under a JavaScript name that differs from the Scala one. */
export class Renames {
  constructor();
  /** Evaluates a script. */
  evaluate(hex: string): string;
  /** Evaluates a script against a budget. */
  evaluate(hex: string, budget: number): string;
  /** Two differently named Scala methods share one exported name. */
  run(x: number): number;
  /** The string arm of `run`. */
  run(x: string): string;
  /** Exported under its own name and under an alias. */
  aliased(): number;
  /** Exported under its own name and under an alias. */
  both(): number;
  /** A field exported under a shorter name. */
  readonly ver: string;
}

/** @JSExportAll implies a bare @JSExport on every public member; an alias adds to it. */
export class RenamesAll {
  constructor();
  /** Reachable as `plain` and as `extra`. */
  extra(): number;
  /** Reachable as `plain` and as `extra`. */
  plain(): number;
}

/** A base class whose members are part of every subclass's JavaScript API. */
export class Shape {
  constructor(kind: string);
  readonly kind: string;
  /** A human-readable description. */
  describe(): string;
  /** Overridden below; only the most derived signature is emitted. */
  sides(): number;
}

export class Statics {
  constructor(v: number);
  readonly v: number;
  static readonly mainnet: Statics;
  static make(v: number, tag?: string): Statics;
  /** Exported as `of`, not as `create`. */
  static of(v: number): Statics;
}

/** Extends a generic base: its members cannot be re-emitted without their type arguments. */
export class StringBox {
  constructor();
}

/** Top-level exported functions from an object. */
export const Tools: {
  /** The library version. */
  readonly version: string;
  /** Doubles. */
  twice(x: number): number;
  concat(a: string, b?: string): string;
};

/** Doubles. */
export function twice(x: number): number;

/** @deprecated Use NewName instead. */
export { NewName as OldName };
/** @deprecated Use twice instead. */
export { twice as double };
