// Generated by scalus-ts-exporter. DO NOT EDIT.

/** One row of `Emulator.getAppliedTxs`. */
export interface AppliedTxInfo {
  /** Hex-encoded 32-byte transaction hash. */
  readonly txHash: string;
  /** The emulator slot at the time this transaction was applied. */
  readonly slot: number;
}

/**
 * One native asset: a policy, a name under it, and how much of it.
 *
 * `policyId` and `assetName` are hex. `unit` is the two concatenated, which is what
 * lucid-evolution and MeshJS call a unit - provided so adapters need no string arithmetic.
 */
export class Asset {
  constructor(policyIdHex: string, assetNameHex: string, amount: bigint);
  readonly policyId: string;
  readonly assetName: string;
  readonly quantity: bigint;
  readonly unit: string;
  /** A plain object with the same fields. Assert on this, never on the handle. */
  toObject(): PlainAsset;
}

/**
 * Network, slot arithmetic and protocol parameters as one coherent triple.
 *
 * This is what an emulator is built from, because a network name alone cannot express what an
 * emulated network needs: slot configuration and protocol parameters vary independently of the
 * network id, and Yaci DevKit's custom `zeroTime`, `slotLength` and short `epochLength` are the
 * standing example.
 *
 * Use `mainnet()`, `preprod()`, `preview()` or `custom()`. The public constructor exists only
 * because Scala.js requires one; it yields an all-zero placeholder.
 */
export class CardanoInfo {
  constructor();
  /**
   * `"mainnet"` or `"testnet"`.
   *
   * Throws for a network id outside those two, which `custom` will not construct. The type is
   * exactly what `custom` accepts, so a value that cannot be named fails loudly rather than
   * degrading to a string no caller asked for.
   */
  readonly network: "mainnet" | "testnet";
  readonly slotConfig: SlotConfig;
  readonly protocolParams: ProtocolParams;
  /**
   * A copy carrying `params` in place of the current protocol parameters. Network and slot
   * config are unchanged.
   */
  withProtocolParams(params: ProtocolParams): CardanoInfo;
  /**
   * A plain object with the same fields.
   *
   * A handle's fields are accessors on the prototype, so `JSON.stringify`, object spread and
   * (the dangerous one) a test framework's `toEqual` all see an empty object on the handle
   * itself. Assert on this instead.
   */
  toObject(): PlainCardanoInfo;
  toString(): string;
  /** Current Cardano mainnet parameters and slot configuration. */
  static mainnet(): CardanoInfo;
  /** Preprod testnet parameters and slot configuration. */
  static preprod(): CardanoInfo;
  /** Preview testnet parameters and slot configuration. */
  static preview(): CardanoInfo;
  /**
   * Yaci DevKit, private testnets, or any other network with its own slot config and parameters.
   * `network` must be `"mainnet"` or `"testnet"`; anything else throws, since those are the only
   * two values `network` can ever read back (see the accessor's doc).
   */
  static custom(network: string, slotConfig: SlotConfig, params: ProtocolParams): CardanoInfo;
}

/**
 * The three Plutus cost models, by language rather than by position - so a caller reads
 * `costModels.PlutusV3`, never `Object.values(costModels)[2]` and a comment explaining why.
 */
export interface CostModels {
  readonly PlutusV1: number[];
  readonly PlutusV2: number[];
  readonly PlutusV3: number[];
}

/**
 * Cost parameters per Plutus language, each in protocol-parameter order and each a safe-integer
 * `number` or a `bigint`. A `CostModels` has them, and so does a plain object from any SDK; a
 * language the transaction does not use may be absent, and other fields are ignored.
 */
export interface CostModelsLike {
  readonly PlutusV1?: readonly (number | bigint)[];
  readonly PlutusV2?: readonly (number | bigint)[];
  readonly PlutusV3?: readonly (number | bigint)[];
}

/** DRep registration entry for `EmulatorInitialState`. */
export interface DRepRegistration {
  /** Credential type: "key" for pub key hash, "script" for script hash. */
  readonly credentialType: "key" | "script";
  /** Hex-encoded 28-byte credential hash */
  readonly credentialHash: string;
  /** Deposit held for this DRep registration, in lovelace. */
  readonly deposit: bigint;
  /**
   * The DRep's metadata anchor as CBOR: a `[url, dataHash]` pair, where `dataHash` is the
   * 32-byte hash of the document the URL points at.
   */
  readonly anchor?: Uint8Array;
}

/** Datum entry for `EmulatorInitialState`. */
export interface DatumEntry {
  /** Hex-encoded 32-byte datum hash */
  readonly hash: string;
  /** The datum itself as CBOR, hex-encoded. Its hash must be `hash`; nothing checks that. */
  readonly datum: string;
}

/** Delegation info returned by `Emulator.getDelegation`. */
export interface DelegationInfo {
  /** Hex-encoded 28-byte pool key hash, or `undefined` if not delegated. */
  readonly poolId?: string;
  /** Reward balance in lovelace. */
  readonly rewards: bigint;
}

/**
 * An in-memory Cardano ledger for tests and local development.
 *
 * A submitted transaction goes through the same phase-1 checks a node performs (fees, value
 * conservation, signatures, validity interval, min-ada, script and datum witnesses, certificates)
 * and then phase-2 Plutus script execution, over most of the node's UTxO ledger rules. Everything
 * lives in this object: no node, no network, no disk. The ledger starts with what you seed it
 * with, and disappears with the process.
 *
 * Build one with `Emulator.create`. The constructor below is deprecated: it takes protocol
 * parameters from the slot configuration alone, so a `SlotConfig.preview` emulator validated
 * transactions against mainnet's parameters. `Emulator.create` takes a `CardanoInfo`, in which the
 * two cannot disagree.
 *
 * @param initialUtxosCbor The UTxO set to start from, as CBOR: a map whose keys are transaction inputs (a `[transactionHash, outputIndex]` pair) and whose values are transaction outputs, as in the Cardano ledger CDDL. This is the same shape `getUtxosCbor` gives back. An array of `[input, output]` pairs, as `Utxo.toCbor` writes each, is read too.
 * @param slotConfig Slot arithmetic for the emulated network, for example `SlotConfig.preview`.
 * @param initialStakeRewards Stake credentials to register before the first transaction: a map from a hex-encoded 28-byte script hash to a reward balance in lovelace, written as a decimal string. Only script credentials can be seeded here; use `Emulator.withState` to seed key credentials. A balance of `"0"` is the usual case: a reward (staking) validator only runs when a transaction withdraws from its address, and a withdrawal of zero lovelace is enough, but the address must already be registered for the transaction to be valid.
 */
export class Emulator {
  /** @deprecated use Emulator.create (since 1.2.0) */
  constructor(initialUtxosCbor: Uint8Array, slotConfig: SlotConfig, initialStakeRewards?: { [key: string]: string });
  /**
   * Network, slot configuration and protocol parameters this emulator validates transactions
   * against, as one coherent triple. For an emulator built with `Emulator.create`, this is
   * exactly the `CardanoInfo` it was created from; for the deprecated constructors, protocol
   * parameters come from `slotConfig` alone (mainnet parameters for `SlotConfig.mainnet`,
   * `UtxoEnv.default`'s parameters otherwise), which is the mismatch `Emulator.create` fixes.
   */
  getCardanoInfo(): CardanoInfo;
  /**
   * The protocol parameters this emulator validates transactions against. Equivalent to
   * `getCardanoInfo().protocolParams`.
   */
  getProtocolParameters(): ProtocolParams;
  /**
   * Runs every Plutus script the transaction triggers and reports what each one costs, resolving
   * inputs against this emulator's UTxO set, slot config, cost models and protocol version.
   *
   * The standalone `evalPlutusScripts` needs all of that passed in, and getting any of it wrong
   * produces plausible, wrong budgets. Here there is nothing to get wrong.
   *
   * Unlike `submitTx`, this throws rather than returning a result object: it answers a question
   * about a transaction, and has no shape in which to say "there was no transaction". Bytes from
   * an untrusted source therefore need a `try`.
   *
   * @throws PlutusScriptEvaluationError if a script fails; it names the redeemer, classifies the failure, carries the script's traces and the arguments the script saw.
   * @throws Error for any other failure: `txCborBytes` does not decode as a transaction, an input no UTxO resolves, a script the transaction does not carry.
   */
  evaluateTx(txCborBytes: Uint8Array): RedeemerBudget[];
  /**
   * As above, plus UTxOs the emulator does not hold - outputs of a transaction not yet
   * submitted, typically. Each is a `Utxo` or an `[input, output]` pair as hex or bytes, as
   * `evaluator.evaluateTx` takes them.
   */
  evaluateTx(txCborBytes: Uint8Array, additionalUtxos: readonly (string | Uint8Array | Utxo)[]): RedeemerBudget[];
  /**
   * Validates a transaction and, if it passes, applies it to the ledger state.
   *
   * Never throws: bytes that are not a transaction at all come back as a failure result with
   * `errorRule: "InvalidTransaction"`, the same shape as a rejection, so a caller handling
   * untrusted bytes needs one branch rather than a branch and a `try`.
   *
   * @param txCborBytes CBOR bytes of the signed transaction, as it would be sent to a node.
   * @returns `{ isSuccess: true, txHash }` when the transaction was accepted, otherwise `{ isSuccess: false, error, errorRule }`, where `errorRule` is the condition that rejected it and `logs` carries the script's trace output (empty unless a Plutus script failed and produced any). A rejected transaction leaves the ledger unchanged.
   */
  submitTx(txCborBytes: Uint8Array): SubmitResult;
  /**
   * Submits a transaction the same way, but keeps a debug build of each script at hand. A
   * release script that fails with no trace output is replayed with its debug build, so the
   * failure message carries real diagnostics instead of nothing.
   *
   * @param txCborBytes CBOR bytes of the signed transaction.
   * @param debugScripts Map from the hex-encoded script hash of a script in the transaction, to the double-CBOR hex of the debug build of that same script. Its Plutus version is taken from the script in the transaction; an entry that matches no script there is ignored, with a console warning.
   * @returns The same shape as the one-argument `submitTx`.
   */
  submitTx(txCborBytes: Uint8Array, debugScripts: { [key: string]: string }): SubmitResult;
  /**
   * The whole UTxO set in a single CBOR map: keys are transaction inputs (a
   * `[transactionHash, outputIndex]` pair), values are transaction outputs, as in the Cardano
   * ledger CDDL. `getAllUtxos` returns the same data instead as one small map per UTxO.
   */
  getUtxosCbor(): Uint8Array;
  /**
   * The UTxOs that sit at one address.
   *
   * @param addressBech32 The address in bech32 form, for example `addr_test1...`.
   * @returns One CBOR map per UTxO, each holding exactly one input-to-output entry, so a single UTxO can be decoded and passed around on its own.
   * @deprecated use getUtxos(filter) with an address filter (since 1.2.0)
   */
  getUtxosForAddress(addressBech32: string): Uint8Array[];
  /**
   * Every UTxO in the ledger.
   *
   * @returns One CBOR map per UTxO, each holding exactly one input-to-output entry. Use `getUtxosCbor` for the whole set in one map instead.
   * @deprecated use getUtxos() (since 1.2.0)
   */
  getAllUtxos(): Uint8Array[];
  /** Every UTxO in the ledger, as `Utxo` handles. */
  getUtxos(): Utxo[];
  /**
   * The UTxOs matching `filter`. Filtering happens in the ledger, so only matches cross into
   * JavaScript - no `Utxo` handle is ever built for a row the filter would drop.
   *
   * Every field given is ANDed together; an empty filter matches everything. `outRefs` is the
   * one field that is itself a disjunction: it matches any of the given refs, not all of them.
   *
   * @throws Error if the filter carries a field `UtxoFilter` does not declare. An unknown field cannot be honoured, and ignoring it would silently widen the query - a misspelt `{ adress: ... }` would hand back every UTxO in the ledger rather than one address's.
   */
  getUtxos(filter: UtxoFilter): Utxo[];
  /**
   * The reward balance of a stake credential, key or script.
   *
   * @param rewardAddressBech32 The reward (stake) address in bech32 form, for example `stake1...` or `stake_test1...`. The address carries which kind of credential it names, so this works for a key credential too - unlike the deprecated `Uint8Array` form this replaces, which only ever built a script credential.
   * @returns The balance in lovelace, or `undefined` if that credential is not registered.
   */
  getStakeReward(rewardAddressBech32: string): bigint | undefined;
  /**
   * Moves the clock to an absolute slot, forwards or backwards. Only validity intervals and
   * time-aware scripts see the difference; no blocks are produced in between and no rewards are
   * paid out. A fractional value is truncated.
   */
  setSlot(slot: number): void;
  /** The current slot number of the emulator. */
  getSlot(): number;
  /** Advance the current slot by `n` slots. */
  tick(n: number): void;
  /**
   * POSIX time in milliseconds at which the emulator's current slot starts. Equivalent to
   * `getCardanoInfo().slotConfig.slotToTime(getSlot())`.
   */
  getTime(): number;
  /**
   * Moves the clock to the slot containing this POSIX time - the inverse of `getTime`. A
   * fractional slot is truncated, the same as `setSlot`.
   */
  setTime(posixMillis: number): void;
  /**
   * Whether a transaction with this hash was accepted by this emulator.
   *
   * @param txHashHex Hex-encoded 32-byte transaction hash.
   */
  hasTx(txHashHex: string): boolean;
  /**
   * Whether a transaction with this hash was accepted by this emulator, as a status string
   * rather than a boolean. Always one of the two values below: with no mempool and immediate
   * application, there is no pending state to report.
   *
   * @param txHashHex Hex-encoded 32-byte transaction hash.
   */
  getTransactionStatus(txHashHex: string): "Confirmed" | "NotFound";
  /**
   * Looks up a previously applied transaction by hash.
   *
   * @param txHashHex Hex-encoded 32-byte transaction hash.
   * @returns The transaction as CBOR, or `undefined` if this emulator never applied it.
   */
  getTransaction(txHashHex: string): Uint8Array | undefined;
  /** Every transaction this emulator has applied, oldest first. */
  getAppliedTxs(): AppliedTxInfo[];
  /**
   * The pool a stake credential delegates to, and its reward balance.
   *
   * @param rewardAddressBech32 The reward (stake) address in bech32 form, for example `stake1...` or `stake_test1...`.
   * @returns `poolId` is `undefined` when the credential delegates to no pool. `rewards` is `0n` both for a registered credential with no rewards and for one that was never registered, so use `getStakeReward` when you need to tell the two apart.
   */
  getDelegation(rewardAddressBech32: string): DelegationInfo;
  /**
   * Live stake per registered stake credential: the lovelace sitting at addresses delegating to
   * it, plus its reward balance, and the pool it delegates to. Not a reward calculation -
   * nothing is paid out.
   */
  getStakeDistribution(): StakeDistributionEntry[];
  /**
   * Looks a datum up by its hash, across the datums seeded into this emulator and the ones
   * witnessed by accepted transactions.
   *
   * @param datumHashHex Hex-encoded 32-byte datum hash.
   * @returns The datum as CBOR, or `undefined` if this emulator has never seen it.
   */
  getDatum(datumHashHex: string): Uint8Array | undefined;
  /**
   * Adds a UTxO to the ledger directly, bypassing transaction validation. Useful for seeding a
   * UTxO a later transaction will spend, without the ceremony of a genesis transaction for it.
   * Overwrites any UTxO already sitting at the same input.
   *
   * @throws Error if `utxo` is not a `Utxo`. A plain `{ txHash, outputIndex, address, value }` object is the natural thing for an untyped caller to build, and it carries none of the parsed ledger pair this reads, so it would otherwise fail a frame later with an unreadable `undefined (of class java.lang.Void)`.
   */
  addUtxo(utxo: Utxo): void;
  /**
   * Removes a UTxO from the ledger directly, bypassing transaction validation. A no-op if no
   * UTxO sits at that input.
   */
  removeUtxo(outRef: OutRef): void;
  /**
   * An independent copy of the whole ledger state: UTxOs, registrations and rewards, the datum
   * store, the accepted transactions, and the current slot. The copy and the original evolve
   * separately from then on, so one expensive setup can branch into several test scenarios
   * without being rebuilt.
   */
  snapshot(): Emulator;
  /**
   * An emulator for a network, with an empty ledger.
   *
   * @param info Network, slot configuration and protocol parameters, as one coherent triple - see the class doc for why this replaces a bare `slotConfig` parameter.
   */
  static create(info: CardanoInfo): Emulator;
  /**
   * An emulator for a network, seeded with UTxOs and registrations.
   *
   * Unlike the older constructors, protocol parameters, network id and slot config come from one
   * `CardanoInfo`, so they cannot disagree - fixing the bug where a `SlotConfig.preview`
   * emulator would validate transactions against mainnet's protocol parameters.
   *
   * @param info Network, slot configuration and protocol parameters, as one coherent triple.
   * @param options UTxOs and registrations to start from. Every field is optional.
   */
  static create(info: CardanoInfo, options: EmulatorOptions): Emulator;
  /**
   * Creates an emulator seeded with a full starting ledger state: UTxOs, and optionally stake
   * credentials, stake pools, DReps and datums. Unlike the constructor, this takes both key and
   * script stake credentials, and takes hashes as hex rather than CBOR.
   *
   * @param state The starting state. Every field except `utxos` may be left out.
   * @param slotConfig Slot arithmetic for the emulated network.
   * @deprecated use Emulator.create (since 1.2.0)
   */
  static withState(state: EmulatorInitialState, slotConfig: SlotConfig): Emulator;
  /**
   * Creates an emulator whose ledger holds one output per address, each carrying only ada. This
   * is the quickest way to get a funded wallet or two for a test.
   *
   * @param addressesBech32 The addresses to fund, in bech32 form.
   * @param slotConfig Slot arithmetic for the emulated network.
   * @param lovelacePerAddress Lovelace in each output. Defaults to `10_000_000_000n`, that is 10 000 ada.
   * @deprecated use Emulator.create (since 1.2.0)
   */
  static withAddresses(addressesBech32: readonly string[], slotConfig: SlotConfig, lovelacePerAddress?: bigint): Emulator;
}

/** Ledger state to seed an emulator with, passed to `Emulator.withState`. Only `utxos` is required. */
export interface EmulatorInitialState {
  /**
   * The starting UTxO set as CBOR: a map from transaction input (a
   * `[transactionHash, outputIndex]` pair) to transaction output, as in the Cardano ledger CDDL.
   */
  readonly utxos: Uint8Array;
  /**
   * Stake credentials that count as already registered, with their reward balances and, if you
   * want, the pool each delegates to.
   */
  readonly stakeRegistrations?: readonly StakeRegistration[];
  /** Stake pools that count as already registered, so transactions may delegate to them. */
  readonly poolRegistrations?: readonly PoolRegistration[];
  /** DReps that count as already registered, so transactions may delegate votes to them. */
  readonly drepRegistrations?: readonly DRepRegistration[];
  /**
   * Datums to put in the emulator's datum store, where `getDatum` looks them up by hash. The
   * store is only a lookup table: every accepted transaction adds the datums it witnesses to it,
   * and validation still requires a transaction to carry the datums it needs.
   */
  readonly datums?: readonly DatumEntry[];
}

/**
 * Everything an emulator may start with beyond its chain parameters, passed to `Emulator.create`.
 * Every field is optional.
 */
export interface EmulatorOptions {
  /** UTxOs to start from. */
  readonly utxos?: readonly Utxo[];
  /** Starting slot. Defaults to the slot containing `Date.now()`. */
  readonly slot?: number;
  /**
   * Stake credentials that count as already registered, with their reward balances and, if you
   * want, the pool each delegates to.
   */
  readonly stakeRegistrations?: readonly StakeRegistration[];
  /** Stake pools that count as already registered, so transactions may delegate to them. */
  readonly poolRegistrations?: readonly PoolRegistration[];
  /** DReps that count as already registered, so transactions may delegate votes to them. */
  readonly drepRegistrations?: readonly DRepRegistration[];
  /**
   * Datums to put in the emulator's datum store, where `getDatum` looks them up by hash. The
   * store is only a lookup table: every accepted transaction adds the datums it witnesses to it,
   * and validation still requires a transaction to carry the datums it needs.
   */
  readonly datums?: readonly DatumEntry[];
}

/**
 * Why a script did not succeed.
 *
 * Branch on `code` rather than on `message`, whose wording may improve. `INTERNAL_ERROR` means
 * a defect in Scalus, not a problem with the script: report it.
 */
export interface EvaluationError {
  /**
   * `SCRIPT_FAILURE`: the script failed, for example by evaluating `error`. `BUILTIN_FAILURE`: a
   * builtin rejected its arguments. `INVALID_RETURN_VALUE`: a Plutus V3 script returned
   * something other than unit. `OUT_OF_BUDGET`: the script spent more than `maxBudget`.
   * `INTERNAL_ERROR`: a defect in Scalus.
   */
  readonly code: "SCRIPT_FAILURE" | "BUILTIN_FAILURE" | "INVALID_RETURN_VALUE" | "OUT_OF_BUDGET" | "INTERNAL_ERROR";
  /** What went wrong, in prose. The wording may change between releases. */
  readonly message: string;
}

/** Factories for `EvaluationOptions`. A plain object literal with the same fields works too. */
export const EvaluationOptions: {
  /**
   * Options from a `ProtocolParams` handle, as returned by `CardanoInfo`, an emulator's
   * `getProtocolParameters()`, or `ProtocolParams.fromBlockfrostJson`.
   *
   * @throws TypeError if the parameters have no cost model for `plutusVersion`
   */
  fromProtocolParams(plutusVersion: "PlutusV1" | "PlutusV2" | "PlutusV3", params: ProtocolParams): EvaluationOptions;
  /**
   * Options from Scalus's bundled mainnet snapshot at protocol version 11. It makes no network
   * request, so it does not follow later parameter changes.
   */
  mainnet(plutusVersion: "PlutusV1" | "PlutusV2" | "PlutusV3"): EvaluationOptions;
};

/**
 * How to run one script: the language, the protocol version, the cost model and, optionally, a
 * budget limit.
 */
export interface EvaluationOptions {
  /**
   * Which Plutus language the script is written in. The script bytes do not carry it, and the
   * same bytes cost differently under different languages.
   */
  readonly plutusVersion: "PlutusV1" | "PlutusV2" | "PlutusV3";
  /**
   * The Cardano major protocol version to evaluate under. It selects the builtin semantics and
   * the costing rules.
   */
  readonly protocolMajorVersion: number;
  /**
   * That language's cost parameters, in protocol-parameter order, each a safe-integer `number`
   * or a `bigint`. The factories fill it with numbers.
   *
   * Any length is accepted. A builtin whose parameters the array does not reach is priced beyond
   * any budget, as in Plutus.
   */
  readonly costModel: readonly (number | bigint)[];
  /**
   * The most the script may spend, for example the ex-units its redeemer declares. A script that
   * exceeds it stops with `OUT_OF_BUDGET`. Without it, execution is not bounded.
   */
  readonly maxBudget?: ExUnitsLike;
}

/** Outcome of evaluating one Plutus script. Read `isSuccess` first. */
export class EvaluationResult {
  constructor(isSuccess: boolean, budget: ExUnits, logs: readonly string[], profileJson?: string);
  /** Whether the script ran to completion and returned a value the ledger accepts. */
  readonly isSuccess: boolean;
  /** Units the machine spent. On failure, what was spent before the script failed. */
  readonly budget: ExUnits;
  /**
   * Trace output the script emitted, oldest first. From the deprecated `evaluateScript` and
   * `evaluateScriptProfile`, a failure's message comes first.
   */
  readonly logs: string[];
  /** Profiling data as JSON; set only by the deprecated `evaluateScriptProfile`. */
  readonly profileJson?: string;
  /** Why the script did not succeed. Set by `evaluator.evaluateScript` on failure. */
  readonly error?: EvaluationError;
}

/**
 * Execution units: what a script costs to run, in abstract machine memory and steps. A transaction
 * pays a fee for the units its scripts declare, and the ledger rejects it if a script goes over
 * what it declared.
 */
export class ExUnits {
  constructor(memory: bigint, steps: bigint);
  readonly memory: bigint;
  readonly steps: bigint;
  /** The units as decimal strings, so `JSON.stringify` works: it throws on a `bigint`. */
  toJSON(): { memory: string; steps: string };
}

/**
 * Execution units as a plain record: `memory` and `steps`, each a safe-integer `number` or a
 * `bigint`. An `ExUnits` fits, and so does any `{ memory, steps }` object.
 */
export interface ExUnitsLike {
  readonly memory: number | bigint;
  readonly steps: number | bigint;
}

/** Identifies one transaction output: the pair a `TransactionInput` is made of. */
export interface OutRef {
  readonly txHash: string;
  readonly outputIndex: number;
}

/** The structural form of {@link Asset}. */
export interface PlainAsset {
  readonly policyId: string;
  readonly assetName: string;
  readonly quantity: bigint;
  readonly unit: string;
}

/** The structural form of {@link CardanoInfo}. */
export interface PlainCardanoInfo {
  readonly network: string;
  readonly slotConfig: SlotConfig;
  readonly protocolParams: PlainProtocolParams;
}

/** The structural form of {@link ProtocolParams}. */
export interface PlainProtocolParams {
  readonly txFeePerByte: number;
  readonly txFeeFixed: number;
  readonly maxTxSize: number;
  readonly maxValueSize: number;
  readonly stakeAddressDeposit: bigint;
  readonly stakePoolDeposit: bigint;
  readonly dRepDeposit: bigint;
  readonly govActionDeposit: bigint;
  readonly utxoCostPerByte: bigint;
  readonly priceMemory: number;
  readonly priceSteps: number;
  readonly maxTxExecutionMemory: bigint;
  readonly maxTxExecutionSteps: bigint;
  readonly collateralPercentage: number;
  readonly maxCollateralInputs: number;
  readonly minFeeRefScriptCostPerByte: number;
  readonly protocolMajorVersion: number;
  readonly costModels: CostModels;
}

/** The structural form of {@link Utxo}. */
export interface PlainUtxo {
  readonly txHash: string;
  readonly outputIndex: number;
  readonly address: string;
  readonly value: PlainValue;
  readonly datumHash?: string;
  readonly inlineDatum?: Uint8Array;
  readonly scriptRef?: Uint8Array;
  readonly scriptLanguage?: string;
}

/** The structural form of {@link Value}. */
export interface PlainValue {
  readonly coin: bigint;
  readonly assets: PlainAsset[];
}

/**
 * Thrown by `evaluator.evaluateTx`, `evalPlutusScripts` and `Emulator.evaluateTx` when a Plutus
 * script fails. Extends `Error`, so `instanceof Error`, `.stack` and unhandled-rejection output
 * all behave normally.
 *
 * `args` is an own property but not an enumerable one: it holds the script context, and printing
 * kilobytes of hex by default would bury the fields that say what failed.
 *
 * From JavaScript, construct with `(message, logs)`.
 */
export class PlutusScriptEvaluationError extends Error {
  /**
   * The constructor of releases before 1.3. An error built through it has no redeemer, hash,
   * code or arguments.
   */
  constructor(message: string, logs: readonly string[]);
  /** The failing script's own `trace` output, oldest first. Empty if it emitted none. */
  readonly logs: string[];
  /** Which redeemer failed. Its `budget` is what the script spent before it failed. */
  readonly redeemer?: RedeemerBudget;
  /** Hash of the failing script, as lowercase hex. */
  readonly scriptHash?: string;
  /** Why it failed, classified the same way `evaluator.evaluateScript` classifies. */
  readonly code?: "SCRIPT_FAILURE" | "BUILTIN_FAILURE" | "INVALID_RETURN_VALUE" | "OUT_OF_BUDGET" | "INTERNAL_ERROR";
  /**
   * The `Data` arguments the script was applied to, each as CBOR hex, in order: for a `PlutusV3`
   * script the script context alone, for a `PlutusV1` or `PlutusV2` spend the datum, the redeemer
   * and the script context.
   */
  readonly args?: readonly string[];
  readonly name: string;
}

/** Pool registration entry for `EmulatorInitialState`. */
export interface PoolRegistration {
  /**
   * The pool's parameters, as one CBOR-encoded Cardano certificate: the whole 10-element
   * `pool_registration` array, tag `3` first, then operator key hash, VRF key hash, pledge,
   * cost, margin, reward account, owners, relays and metadata. The bare parameter list without
   * the certificate tag is rejected.
   */
  readonly params: Uint8Array;
}

/**
 * The protocol parameters a transaction is built and validated against.
 *
 * These are the fields a transaction builder reads - the ones MeshJS's and the Evolution SDK's own
 * parameter types both carry. Fee rates, sizes, percentages and counts are `number`; every
 * deposit, `utxoCostPerByte` and the execution-unit maxima are `bigint`, because lovelace exceeds
 * `Number.MAX_SAFE_INTEGER`.
 *
 * Get them from `CardanoInfo.mainnet()`/`preprod()`/`preview()`/`custom()`, from an emulator's
 * `getProtocolParameters()`, or from `ProtocolParams.fromBlockfrostJson`. The public constructor
 * exists only because Scala.js requires one; it yields all-zero placeholder parameters and is not
 * a supported way to get real ones.
 */
export class ProtocolParams {
  constructor();
  readonly txFeePerByte: number;
  readonly txFeeFixed: number;
  readonly maxTxSize: number;
  readonly maxValueSize: number;
  readonly stakeAddressDeposit: bigint;
  readonly stakePoolDeposit: bigint;
  readonly dRepDeposit: bigint;
  readonly govActionDeposit: bigint;
  readonly utxoCostPerByte: bigint;
  readonly priceMemory: number;
  readonly priceSteps: number;
  readonly maxTxExecutionMemory: bigint;
  readonly maxTxExecutionSteps: bigint;
  readonly collateralPercentage: number;
  readonly maxCollateralInputs: number;
  readonly minFeeRefScriptCostPerByte: number;
  readonly protocolMajorVersion: number;
  /**
   * The three cost models, keyed by language rather than by position.
   *
   * A `def`, like every other accessor - it appears in the `.d.ts` as a readonly property, same
   * as `txFeePerByte` and the rest, because a parameterless Scala.js member always does.
   */
  readonly costModels: CostModels;
  /**
   * Render as Blockfrost's `/epochs/{n}/parameters` JSON - what MeshJS's and the Evolution SDK's
   * own Blockfrost adapters already know how to parse.
   */
  toBlockfrostJson(): string;
  /**
   * A plain object with the same fields.
   *
   * A handle's fields are accessors on the prototype, so `JSON.stringify`, object spread and
   * (the dangerous one) a test framework's `toEqual` all see an empty object on the handle
   * itself. Assert on this instead.
   */
  toObject(): PlainProtocolParams;
  toString(): string;
  /**
   * Reads protocol parameters from Blockfrost's `/epochs/{n}/parameters` JSON.
   *
   * The only JSON entry point exported to JavaScript. `cardano-cli query protocol-parameters`
   * output is readable from Scala but not from here: it is devops-tool output rather than
   * something a browser or Node client has to hand, and exporting the reader would pull the JSON
   * derivation for six more ledger types into the bundle. To configure an evaluation from any
   * other provider, put its cost array in an `EvaluationOptions` record instead of parsing a
   * whole parameter set.
   */
  static fromBlockfrostJson(json: string): ProtocolParams;
}

/**
 * One redeemer of a transaction, together with the execution budget its script really used. `tag`
 * and `index` together say which script this is, and match the redeemer in the transaction.
 *
 * `tag` is why the script ran: `"Spend"` for a script input, `"Mint"` for a minting policy,
 * `"Cert"` for a certificate, `"Reward"` for a withdrawal, `"Voting"` for a vote, and
 * `"Proposing"` for a governance proposal.
 */
export class RedeemerBudget {
  constructor(tag: "Spend" | "Mint" | "Cert" | "Reward" | "Voting" | "Proposing", index: number, budget: ExUnits);
  /** Why the script ran, and so which group `index` counts within. */
  readonly tag: "Spend" | "Mint" | "Cert" | "Reward" | "Voting" | "Proposing";
  /**
   * Position within the group named by `tag`, counting from 0: for `"Spend"` it indexes the
   * transaction's inputs in ledger order, for `"Mint"` its minting policies, and so on.
   */
  readonly index: number;
  /** What this redeemer's script actually spent, to put in the transaction. */
  readonly budget: ExUnits;
}

/**
 * The `Scalus` namespace object.
 *
 * @deprecated Use the top-level exports instead; this namespace object remains for backwards compatibility. `applyDataArgToScript` becomes `uplc.applyParamsToScript`, `evaluateScript` becomes `evaluator.evaluateScript` with an `EvaluationOptions`, `evalPlutusScripts` becomes `evaluator.evaluateTx`, and `evaluateScriptProfile` is not replaced.
 */
export const Scalus: {
  /**
   * Applies one argument to a Plutus script and returns the applied script. Use it to bake a
   * parameter into a parameterized validator before you compute its script hash.
   *
   * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
   * @param data The argument in the standard Plutus Data JSON encoding, for example `{"int":42}` or `{"constructor":0,"fields":[{"bytes":"deadbeef"}]}`.
   * @returns The double-CBOR-encoded hex representation of the script with the argument applied.
   * @deprecated (since 1.2.0) Use `uplc.applyParamsToScript`, which takes a list of parameters and accepts hex or bytes. It reads Data as CBOR rather than JSON, so convert first; `uplc.applyParamsToScript(script, [cborHex])` then returns what this function returns.
   */
  applyDataArgToScript(doubleCborHex: string, data: string): string;
  /**
   * Evaluates a Plutus script on its own, with no transaction around it. The script runs on a
   * Plutus V3 machine with the mainnet cost models of the current mainnet protocol major version
   * (11, van Rossem).
   *
   * This never throws. A script that fails, and a script whose hex cannot even be decoded, both
   * come back as a result with `isSuccess: false` and the message in `logs[0]`.
   *
   * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
   * @returns The outcome, with the units spent and the trace logs.
   * @deprecated (since 1.2.0) Use `evaluator.evaluateScript(script, args, options)`, which takes the language, protocol version and cost model explicitly instead of assuming Plutus V3 on mainnet, and reports why a script failed in `error`. `EvaluationOptions.mainnet("PlutusV3")` reproduces this function's configuration.
   */
  evaluateScript(doubleCborHex: string): EvaluationResult;
  /**
   * Evaluates a Plutus script with profiling enabled.
   *
   * Same evaluation and same never-throws contract as {@link evaluateScript}, but the result also
   * carries the machine's profiling data as JSON in `profileJson`: cost per source location,
   * cost per builtin, and the transition edges between them.
   *
   * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
   * @returns The outcome, with `profileJson` populated.
   * @deprecated (since 1.2.0) Not replaced: `evaluator.evaluateScript` does not profile. Attributing cost to source lines needs the compiler output that produced the script, so profile from the JVM, where `PlutusVM.evaluateScriptProfile` and `ProfileFormatter` render the full report. This function keeps working meanwhile.
   */
  evaluateScriptProfile(doubleCborHex: string): EvaluationResult;
  /**
   * Evaluates every Plutus script a transaction runs, and reports what each one costs. Use it to
   * fill in a transaction's execution units before you balance and submit it.
   *
   * @param txCborBytes CBOR bytes of the transaction whose scripts should run.
   * @param utxoCborBytes CBOR bytes of the UTxO set the scripts see: a CBOR map whose keys are transaction inputs (a `[transactionHash, outputIndex]` pair) and whose values are transaction outputs, as in the Cardano ledger CDDL. It must resolve every input and reference input of the transaction.
   * @param slotConfig Slot arithmetic for the target network, used to turn the transaction's validity interval into the POSIX times the scripts observe.
   * @param costModels One cost model per Plutus language version, indexed by position: `costModels[0]` is Plutus V1, `[1]` is V2, `[2]` is V3. Each inner array holds that version's cost parameters in protocol-parameter order. Give a model for every version the transaction uses; since the position is the version, an earlier version cannot be skipped.
   * @param protocolMajorVersion Cardano protocol major version, which picks the builtin semantics and the costing rules. Defaults to the current mainnet version, 11 (van Rossem).
   * @returns One entry per redeemer of the transaction, carrying the units that redeemer's script spent.
   * @throws PlutusScriptEvaluationError if a script fails; it names the redeemer, classifies the failure, carries the script's traces and the arguments the script saw.
   * @throws Error for any other failure: malformed transaction or UTxO CBOR, an input no entry of the UTxO set resolves, a script the transaction does not carry.
   * @deprecated (since 1.2.0) Use `evaluator.evaluateTx(tx, utxos, slotConfig, costModels, protocolMajorVersion)`, the same evaluation. It takes the resolved inputs as CBOR `[input, output]` pairs instead of one map, the cost models by language name instead of by position, and the protocol version explicitly instead of defaulting to mainnet's.
   */
  evalPlutusScripts(txCborBytes: Uint8Array, utxoCborBytes: Uint8Array, slotConfig: SlotConfig, costModels: readonly (readonly number[])[], protocolMajorVersion?: number): RedeemerBudget[];
};

/**
 * Slot and epoch configuration for a Cardano network.
 *
 * Encodes the linear (post-Byron) era as an anchor point: slot `zeroSlot` starts at `zeroTime`
 * (POSIX milliseconds) and falls at the beginning of epoch `zeroEpoch`; slots are `slotLength`
 * milliseconds long and epochs are `epochLength` slots long.
 */
export class SlotConfig {
  constructor(zeroTime: number, zeroSlot: number, slotLength: number, epochLength?: number, zeroEpoch?: number);
  /** POSIX time in milliseconds at which slot `zeroSlot` starts. */
  readonly zeroTime: number;
  /** The slot this config is anchored at: the first slot of the linear (post-Byron) era. */
  readonly zeroSlot: number;
  /** Slot length in milliseconds. */
  readonly slotLength: number;
  /** Epoch length in slots. */
  readonly epochLength: number;
  /** Number of the epoch that begins at `zeroSlot`. */
  readonly zeroEpoch: number;
  /** POSIX time in milliseconds at which the given slot starts. */
  slotToTime(slot: number): number;
  /**
   * The slot that contains the given POSIX time in milliseconds.
   *
   * The result is fractional whenever the time does not land exactly on a slot boundary, and
   * with one-second slots `timeToSlot(Date.now())` almost never does. Round it yourself before
   * you use it as a slot number, for example with `Math.floor`; `Emulator.setSlot` truncates a
   * fractional value rather than rejecting it.
   */
  timeToSlot(time: number): number;
  /** Epoch containing the given slot. Slots before `zeroSlot` are clamped to `zeroEpoch`. */
  epochOf(slot: number): number;
  /** First slot of the given epoch (for epochs >= `zeroEpoch`). */
  firstSlotOfEpoch(epoch: number): number;
  /** Mainnet slot configuration starting at Shelley era (slot 4492800 = start of epoch 208) */
  static readonly mainnet: SlotConfig;
  /** Preview testnet slot configuration starting at Shelley era (1-day epochs) */
  static readonly preview: SlotConfig;
  /** Preprod testnet slot configuration (slot 86400 = start of epoch 4, after 4 Byron epochs) */
  static readonly preprod: SlotConfig;
}

/**
 * The slot arithmetic `evaluator.evaluateTx` reads. A `SlotConfig` has it, and so does a plain
 * object from any SDK; other fields are ignored.
 */
export interface SlotConfigLike {
  /** POSIX time in milliseconds at which slot `zeroSlot` starts. */
  readonly zeroTime: number | bigint;
  /** The slot the configuration is anchored at. */
  readonly zeroSlot: number | bigint;
  /** Slot length in milliseconds. */
  readonly slotLength: number;
}

/** One row of `Emulator.getStakeDistribution`. */
export interface StakeDistributionEntry {
  /**
   * Hex-encoded 28-byte credential hash - a key hash or a script hash, with no discriminator,
   * the same convention `UtxoFilter.paymentCredential` uses.
   */
  readonly credential: string;
  /** Hex-encoded 28-byte pool key hash, or `undefined` if this credential delegates to no pool. */
  readonly pool?: string;
  /** Live stake: the lovelace sitting at addresses delegating to this credential. */
  readonly stake: bigint;
  /** This credential's reward balance. */
  readonly rewards: bigint;
}

/** Stake registration entry for `EmulatorInitialState`. */
export interface StakeRegistration {
  /** Credential type: "key" for pub key hash, "script" for script hash. */
  readonly credentialType: "key" | "script";
  /** Hex-encoded 28-byte credential hash */
  readonly credentialHash: string;
  /** Starting reward balance in lovelace. */
  readonly rewards: bigint;
  /**
   * Hex-encoded 28-byte key hash of the pool this credential delegates to. Leave it out for a
   * credential that is registered but delegates to nothing.
   */
  readonly delegatedTo?: string;
}

/**
 * Result of `Emulator.submitTx`. Read `isSuccess` first: `txHash` is present only on success,
 * `error`/`errorRule` only on failure. `logs` is the exception - always an array, empty when there
 * is nothing to report.
 */
export interface SubmitResult {
  readonly isSuccess: boolean;
  /** Transaction hash hex; present on success. */
  readonly txHash?: string;
  /** Error message; present on failure. */
  readonly error?: string;
  /**
   * The condition that rejected the transaction; present on failure.
   *
   * Four conditions have a name of their own, because a caller branches on them rather than on
   * the rule: `UtxoNotAvailable` (an input this transaction spends is not in the ledger - the
   * ledger rules `BadInputsUTxO` and `BadAllInputsUTxO` are deliberately folded into this one
   * name, since they are one condition), `TransactionExpired`, `ValueNotConserved` and
   * `ScriptFailure` (a native or a Plutus script did not validate). Bytes that are not a
   * transaction at all give `InvalidTransaction`.
   *
   * Every other rejection reports the ledger rule's own name: `FeesOk`, `MissingKeyHashes`,
   * `BadCollateralInputsUTxO`, `BadReferenceInputsUTxO`, `InvalidScriptDataHash`, `Datums`,
   * `ExUnitsExceedMax`, `WithdrawalsNotInRewards` and the rest.
   *
   * Stable enough to assert on in a test, unlike `error`; a name here does not minify away or
   * otherwise change under refactoring, unlike `getClass.getSimpleName`.
   */
  readonly errorRule?: string;
  /** Script trace logs, oldest first. Always an array; empty when the script produced none. */
  readonly logs: string[];
}

/**
 * One unspent output: where it is, whose it is, and what it holds.
 *
 * Holds the ledger's own input and output, so a `Utxo` a query hands you can be handed straight
 * back - to `evaluateTx` or `addUtxo` - with no encoding step in between. Constructing one from
 * strings costs nothing until an accessor needs the parsed form.
 */
export class Utxo {
  constructor(txHash0: string, outputIndex0: number, address0: string, value0: Value);
  readonly txHash: string;
  readonly outputIndex: number;
  /**
   * Bech32 address.
   *
   * Throws when the ledger address cannot be bech32-encoded - which happens only for an address
   * on a network id outside `{Mainnet, Testnet}` (`Network.Other`), since bech32 has no defined
   * human-readable prefix for an arbitrary network id. This is a genuine "cannot represent"
   * case, not malformed input, so it fails loudly rather than degrading to hex: a caller
   * comparing, filtering on, or handing this value to a wallet needs to know its address is
   * unrepresentable, not receive a string that silently is not one.
   */
  readonly address: string;
  readonly value: Value;
  /** The datum hash, when the output references a datum rather than carrying one. */
  readonly datumHash?: string;
  /** The datum itself as CBOR, when the output carries it inline. */
  readonly inlineDatum?: Uint8Array;
  /** The reference script as CBOR, when the output carries one. */
  readonly scriptRef?: Uint8Array;
  /** Which language `scriptRef` is written in. */
  readonly scriptLanguage?: string;
  /**
   * This UTxO as CBOR `[input, output]`, CIP-30's `transaction_unspent_output`: the shape
   * `evaluator.evaluateTx` reads, and what CML, CST and a wallet's `getUtxos()` produce.
   */
  toCbor(): Uint8Array;
  /** A copy carrying `hash` as a datum hash, in place of whatever datum this output had. */
  withDatumHash(hash: string): Utxo;
  /** A copy carrying the CBOR-decoded value of `cbor` as its inline datum. */
  withInlineDatum(cbor: Uint8Array): Utxo;
  /**
   * A copy carrying `script` as its reference script.
   *
   * Takes the script as `{ type, script }`, the shape Lucid's `Script` has: `script` is hex or
   * bytes, the native-script CBOR for `"Native"`, and for Plutus the program as raw flat, single
   * or double CBOR. Also takes the ledger's `script_ref` CBOR, as `scriptRef` returns it. A
   * Plutus program is stored as given, not checked.
   *
   * @throws TypeError if `script` is neither form, its hex is invalid, or a `"Native"` script or a `script_ref` does not decode
   */
  withScriptRef(script: Uint8Array | { readonly type: "Native" | "PlutusV1" | "PlutusV2" | "PlutusV3"; readonly script: string | Uint8Array }): Utxo;
  /**
   * A plain object with the same fields.
   *
   * A handle's fields are accessors on the prototype, so `JSON.stringify`, object spread and
   * (the dangerous one) a test framework's `toEqual` all see an empty object on the handle
   * itself. Assert on this instead.
   */
  toObject(): PlainUtxo;
  toString(): string;
  /**
   * Read back what `toCbor` wrote: CBOR `[input, output]`. Also reads the one-entry map
   * `{input: output}` that `toCbor` wrote up to 1.2.
   *
   * A map of any other size is rejected, an empty one and a many-entry one alike. Taking the
   * first entry of a many-entry map would drop the rest without a word, and which one survived
   * would be whichever the decoded `Map` happened to iterate first - so a caller who passed a
   * whole UTxO set here (the shape `Emulator.getUtxosCbor` returns) would get one arbitrary UTxO
   * back and no hint that the others existed.
   *
   * @throws Error if the map does not hold exactly one entry.
   */
  static fromCbor(cbor: Uint8Array): Utxo;
}

/** Narrows `getUtxos`. Every field is optional; several may be combined, and they are ANDed. */
export interface UtxoFilter {
  readonly address?: string;
  /**
   * Hex payment-credential hash: matches every address with this payment part, whatever its
   * stake part. This is the query a wallet wants.
   */
  readonly paymentCredential?: string;
  /**
   * Restricts paymentCredential to key or script credentials. Requires paymentCredential;
   * omitted means either kind. Other filters still AND together.
   */
  readonly paymentCredentialType?: "key" | "script";
  /** `"lovelace"`, or a policy id and asset name concatenated as hex. */
  readonly unit?: string;
  /**
   * Matches a UTxO whose input is any of these - a disjunction over this array, unlike the other
   * fields, which AND together.
   */
  readonly outRefs?: readonly OutRef[];
  readonly txHash?: string;
  readonly minLovelace?: bigint;
  /** Applied last, after every other field above has been matched. */
  readonly limit?: number;
}

/**
 * An amount of ada together with any native assets beside it.
 *
 * This wraps the ledger's own `Value`: the object handed to you by a query holds the real thing,
 * so passing it back to the emulator costs no re-encoding.
 */
export class Value {
  constructor(lovelace: bigint);
  constructor(lovelace: bigint, assets: readonly Asset[]);
  /** Lovelace. A `bigint` because the ada supply exceeds `Number.MAX_SAFE_INTEGER`. */
  readonly coin: bigint;
  /** The native assets, in ledger order. Empty for pure ada. */
  readonly assets: Asset[];
  /** This value plus another. Neither operand is modified. */
  plus(other: Value): Value;
  toString(): string;
  /**
   * A plain object with the same fields.
   *
   * Handle accessors live on the prototype, so `JSON.stringify`, spread and (the dangerous one)
   * vitest's `toEqual` all see an empty object, which makes `expect(a).toEqual(b)` pass for two
   * different values. Assert through this instead.
   */
  toObject(): PlainValue;
  /**
   * `n` ada, as lovelace.
   *
   * A named factory rather than a constructor overload on purpose: `new Value(5n)` already means
   * five *lovelace*, so a same-arity constructor meaning five *ada* would be indistinguishable
   * at the call site and silently a million times off. The unit has to be in the name.
   */
  static ada(ada: bigint): Value;
}

/**
 * Applies one argument to a Plutus script and returns the applied script. Use it to bake a
 * parameter into a parameterized validator before you compute its script hash.
 *
 * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
 * @param data The argument in the standard Plutus Data JSON encoding, for example `{"int":42}` or `{"constructor":0,"fields":[{"bytes":"deadbeef"}]}`.
 * @returns The double-CBOR-encoded hex representation of the script with the argument applied.
 * @deprecated (since 1.2.0) Use `uplc.applyParamsToScript`, which takes a list of parameters and accepts hex or bytes. It reads Data as CBOR rather than JSON, so convert first; `uplc.applyParamsToScript(script, [cborHex])` then returns what this function returns.
 */
export function applyDataArgToScript(doubleCborHex: string, data: string): string;

/** The bytes as lowercase hex. */
export function bytesToHex(bytes: Uint8Array): string;

/** A CBOR byte-string envelope, one layer at a time. */
export const cbor: {
  /** Wraps bytes in one CBOR byte string: flat to single CBOR, or single to double. */
  wrapBytes(bytes: Uint8Array): Uint8Array;
  /**
   * Removes one CBOR byte-string layer: double CBOR to single, or single to flat.
   *
   * @throws TypeError if the bytes are not a CBOR byte string
   */
  unwrapBytes(bytes: Uint8Array): Uint8Array;
};

/**
 * The hash a datum is identified by, in an output's datum hash or a witness set.
 *
 * Hashes the CBOR exactly as given: two encodings of the same `Data` hash differently, as on
 * the ledger.
 *
 * @param data the datum, CBOR-encoded `Data`, as hex or bytes
 * @returns the 32-byte hash, as lowercase hex
 */
export function dataHash(data: string | Uint8Array): string;

/**
 * Evaluates every Plutus script a transaction runs, and reports what each one costs. Use it to
 * fill in a transaction's execution units before you balance and submit it.
 *
 * @param txCborBytes CBOR bytes of the transaction whose scripts should run.
 * @param utxoCborBytes CBOR bytes of the UTxO set the scripts see: a CBOR map whose keys are transaction inputs (a `[transactionHash, outputIndex]` pair) and whose values are transaction outputs, as in the Cardano ledger CDDL. It must resolve every input and reference input of the transaction.
 * @param slotConfig Slot arithmetic for the target network, used to turn the transaction's validity interval into the POSIX times the scripts observe.
 * @param costModels One cost model per Plutus language version, indexed by position: `costModels[0]` is Plutus V1, `[1]` is V2, `[2]` is V3. Each inner array holds that version's cost parameters in protocol-parameter order. Give a model for every version the transaction uses; since the position is the version, an earlier version cannot be skipped.
 * @param protocolMajorVersion Cardano protocol major version, which picks the builtin semantics and the costing rules. Defaults to the current mainnet version, 11 (van Rossem).
 * @returns One entry per redeemer of the transaction, carrying the units that redeemer's script spent.
 * @throws PlutusScriptEvaluationError if a script fails; it names the redeemer, classifies the failure, carries the script's traces and the arguments the script saw.
 * @throws Error for any other failure: malformed transaction or UTxO CBOR, an input no entry of the UTxO set resolves, a script the transaction does not carry.
 * @deprecated (since 1.2.0) Use `evaluator.evaluateTx(tx, utxos, slotConfig, costModels, protocolMajorVersion)`, the same evaluation. It takes the resolved inputs as CBOR `[input, output]` pairs instead of one map, the cost models by language name instead of by position, and the protocol version explicitly instead of defaulting to mainnet's.
 */
export function evalPlutusScripts(txCborBytes: Uint8Array, utxoCborBytes: Uint8Array, slotConfig: SlotConfig, costModels: readonly (readonly number[])[], protocolMajorVersion?: number): RedeemerBudget[];

/**
 * Evaluates a Plutus script on its own, with no transaction around it. The script runs on a
 * Plutus V3 machine with the mainnet cost models of the current mainnet protocol major version
 * (11, van Rossem).
 *
 * This never throws. A script that fails, and a script whose hex cannot even be decoded, both
 * come back as a result with `isSuccess: false` and the message in `logs[0]`.
 *
 * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
 * @returns The outcome, with the units spent and the trace logs.
 * @deprecated (since 1.2.0) Use `evaluator.evaluateScript(script, args, options)`, which takes the language, protocol version and cost model explicitly instead of assuming Plutus V3 on mainnet, and reports why a script failed in `error`. `EvaluationOptions.mainnet("PlutusV3")` reproduces this function's configuration.
 */
export function evaluateScript(doubleCborHex: string): EvaluationResult;

/**
 * Evaluates a Plutus script with profiling enabled.
 *
 * Same evaluation and same never-throws contract as {@link evaluateScript}, but the result also
 * carries the machine's profiling data as JSON in `profileJson`: cost per source location,
 * cost per builtin, and the transition edges between them.
 *
 * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
 * @returns The outcome, with `profileJson` populated.
 * @deprecated (since 1.2.0) Not replaced: `evaluator.evaluateScript` does not profile. Attributing cost to source lines needs the compiler output that produced the script, so profile from the JVM, where `PlutusVM.evaluateScriptProfile` and `ProfileFormatter` render the full report. This function keeps working meanwhile.
 */
export function evaluateScriptProfile(doubleCborHex: string): EvaluationResult;

/** Synchronous evaluation of one script, or of every script of a transaction. */
export const evaluator: {
  /**
   * Applies the arguments to the script, runs it, and reports what it cost.
   *
   * A script that fails comes back as a result with `isSuccess: false` and an `error` saying
   * why, together with the budget it spent and the traces it emitted. A Plutus V3 script must
   * return unit (CIP-117); V1 and V2 may return anything, as in the ledger.
   *
   * The script is not checked against the language and protocol you name: a builtin that
   * protocol never had still runs. Whether a chain would accept the script is
   * `Script.isWellFormed`'s question.
   *
   * @param script the script, as hex or bytes of raw flat, single CBOR or double CBOR
   * @param args the arguments, each a CBOR-encoded `Data`, applied left to right
   * @param options the language, protocol version and cost model, and optionally a `maxBudget`
   * @throws TypeError if the script, an argument or the options cannot be read
   */
  evaluateScript(script: string | Uint8Array, args: readonly (string | Uint8Array)[], options: EvaluationOptions): EvaluationResult;
  /**
   * Evaluates every Plutus script of a transaction and reports what each redeemer cost.
   *
   * The resolved inputs arrive as CBOR `[input, output]` pairs, `transaction_unspent_output` in
   * the ledger CDDL: CML's `TransactionUnspentOutput.to_cbor_bytes()`, CST's
   * `TransactionUnspentOutput.toCbor()`, a CIP-30 wallet's `getUtxos()` and `Utxo.toCbor()` all
   * produce it. A `Utxo` itself is taken too, with no encoding step. A later entry with the same
   * input replaces an earlier one.
   *
   * @param tx the transaction, as hex or bytes
   * @param utxos the resolved inputs and reference inputs, each a `Utxo` or an `[input, output]` pair as hex or bytes
   * @param slotConfig the chain's slot arithmetic: a `SlotConfig`, or any object with the same three fields
   * @param costModels cost parameters per language, keyed by name: a `CostModels`, or any object with some of its fields
   * @param protocolMajorVersion picks the builtin semantics and the costing rules
   * @returns one entry per redeemer, carrying the units that redeemer's script spent
   * @throws PlutusScriptEvaluationError if a script fails; it names the redeemer and carries the arguments the script saw
   * @throws TypeError if an input cannot be read as described
   * @throws Error if the transaction evaluator stops for any other reason: an input no pair resolves, a script the transaction does not carry, a missing datum
   */
  evaluateTx(tx: string | Uint8Array, utxos: readonly (string | Uint8Array | Utxo)[], slotConfig: SlotConfigLike, costModels: CostModelsLike, protocolMajorVersion: number): RedeemerBudget[];
  /**
   * As above, with the scripts of the whole transaction limited to `maxBudget` together, as the
   * ledger limits them to the protocol's maximum transaction execution units. A script that
   * would exceed what the scripts before it left fails with `OUT_OF_BUDGET`.
   *
   * @param maxBudget the execution units all the transaction's scripts may spend together
   */
  evaluateTx(tx: string | Uint8Array, utxos: readonly (string | Uint8Array | Utxo)[], slotConfig: SlotConfigLike, costModels: CostModelsLike, protocolMajorVersion: number, maxBudget: ExUnitsLike): RedeemerBudget[];
};

/**
 * The bytes a hex string spells, in either case.
 *
 * @throws TypeError if the string has an odd length or a non-hex character
 */
export function hexToBytes(hex: string): Uint8Array;

/**
 * The hash a script is identified by: its policy id, or its payment credential.
 *
 * Takes the script as `Utxo.withScriptRef` does: `{ type, script }`, with a Plutus program in
 * any CBOR wrapping, or the ledger's `script_ref` CBOR. The wrapping does not change the hash.
 *
 * @returns the 28-byte hash, as lowercase hex
 * @throws TypeError if `script` is neither form, its hex is invalid, or a `"Native"` script or a `script_ref` does not decode
 */
export function scriptHash(script: Uint8Array | { readonly type: "Native" | "PlutusV1" | "PlutusV2" | "PlutusV3"; readonly script: string | Uint8Array }): string;

/**
 * UPLC scripts as bytes.
 *
 * The primitives work on flat program bytes: `decodeToFlat` takes a script in any form a caller
 * holds, and `applyArgs` applies arguments to it. Together with `cbor.wrapBytes` and
 * `bytesToHex` they compose into any envelope a tool expects. `applyParamsToScript` is the
 * common composition in one call. Every member throws a `TypeError` for input it cannot read.
 */
export const uplc: {
  /**
   * The flat program bytes of a script, whatever form it arrives in.
   *
   * Takes hex or bytes of raw flat, single CBOR or double CBOR. Only the envelopes are read, so
   * this is cheap and the script's own bytes come back unchanged; the program is decoded where
   * it is used, by `applyArgs` or the evaluator.
   *
   * @param script the script, as hex or bytes
   * @returns the flat program bytes
   */
  decodeToFlat(script: string | Uint8Array): Uint8Array;
  /**
   * Applies `Data` arguments to a flat program, left to right.
   *
   * @param flat the flat program bytes, as `decodeToFlat` returns them
   * @param args the arguments, each a CBOR-encoded `Data`, as hex or bytes
   * @returns the applied program, as flat bytes
   */
  applyArgs(flat: Uint8Array, args: readonly (string | Uint8Array)[]): Uint8Array;
  /**
   * Applies CBOR-encoded `Data` parameters to a script and returns it as double-CBOR hex.
   *
   * The same contract as Lucid's and Mesh's `applyParamsToScript`: any script form in, the
   * double-CBOR hex their script objects hold out. It is
   * `bytesToHex(cbor.wrapBytes(cbor.wrapBytes(uplc.applyArgs(uplc.decodeToFlat(script),
   * params))))`.
   *
   * @param script the script, as hex or bytes of raw flat, single CBOR or double CBOR
   * @param params the parameters, each a CBOR-encoded `Data`, as hex or bytes
   * @returns the applied script, double-CBOR, as lowercase hex
   */
  applyParamsToScript(script: string | Uint8Array, params: readonly (string | Uint8Array)[]): string;
};

/** @deprecated Use RedeemerBudget instead. */
export { RedeemerBudget as Redeemer };
/** @deprecated Use EvaluationResult instead. */
export { EvaluationResult as Result };
