// Generated by scalus-ts-exporter. DO NOT EDIT.

/** DRep registration entry for `EmulatorInitialState`. */
export interface DRepRegistration {
  /** Credential type: "key" for pub key hash, "script" for script hash. */
  readonly credentialType: "key" | "script";
  /** Hex-encoded 28-byte credential hash */
  readonly credentialHash: string;
  /** Deposit held for this DRep registration, in lovelace. */
  readonly deposit: bigint;
  /**
   * The DRep's metadata anchor as CBOR: a `[url, dataHash]` pair, where `dataHash` is the
   * 32-byte hash of the document the URL points at.
   */
  readonly anchor?: Uint8Array;
}

/** Datum entry for `EmulatorInitialState`. */
export interface DatumEntry {
  /** Hex-encoded 32-byte datum hash */
  readonly hash: string;
  /** The datum itself as CBOR, hex-encoded. Its hash must be `hash`; nothing checks that. */
  readonly datum: string;
}

/** Delegation info returned by `Emulator.getDelegation`. */
export interface DelegationInfo {
  /** Pool key hash bytes, or null if not delegated. */
  readonly poolId: Uint8Array | null;
  /** Reward balance in lovelace. */
  readonly rewards: bigint;
}

/**
 * An in-memory Cardano ledger for tests and local development.
 *
 * A submitted transaction goes through the same phase-1 checks a node performs (fees, value
 * conservation, signatures, validity interval, min-ada, script and datum witnesses, certificates)
 * and then phase-2 Plutus script execution, over most of the node's UTxO ledger rules. Everything
 * lives in this object: no node, no network, no disk. The ledger starts with what you seed it
 * with, and disappears with the process.
 *
 * @param initialUtxosCbor The UTxO set to start from, as CBOR: a map whose keys are transaction inputs (a `[transactionHash, outputIndex]` pair) and whose values are transaction outputs, as in the Cardano ledger CDDL. This is the same shape `getUtxosCbor` gives back.
 * @param slotConfig Slot arithmetic for the emulated network, for example `SlotConfig.preview`.
 * @param initialStakeRewards Stake credentials to register before the first transaction: a map from a hex-encoded 28-byte script hash to a reward balance in lovelace, written as a decimal string. Only script credentials can be seeded here; use `Emulator.withState` to seed key credentials. A balance of `"0"` is the usual case: a reward (staking) validator only runs when a transaction withdraws from its address, and a withdrawal of zero lovelace is enough, but the address must already be registered for the transaction to be valid.
 */
export class Emulator {
  constructor(initialUtxosCbor: Uint8Array, slotConfig: SlotConfig, initialStakeRewards?: { [key: string]: string });
  /**
   * Validates a transaction and, if it passes, applies it to the ledger state.
   *
   * @param txCborBytes CBOR bytes of the signed transaction, as it would be sent to a node.
   * @returns `{ isSuccess: true, txHash }` when the transaction was accepted, otherwise `{ isSuccess: false, error }` naming the rule it broke, plus `logs` when a Plutus script failed and produced trace output. A rejected transaction leaves the ledger unchanged.
   */
  submitTx(txCborBytes: Uint8Array): SubmitResult;
  /**
   * Submits a transaction the same way, but keeps a debug build of each script at hand. A
   * release script that fails with no trace output is replayed with its debug build, so the
   * failure message carries real diagnostics instead of nothing.
   *
   * @param txCborBytes CBOR bytes of the signed transaction.
   * @param debugScripts Map from the hex-encoded script hash of a script in the transaction, to the double-CBOR hex of the debug build of that same script. Its Plutus version is taken from the script in the transaction; an entry that matches no script there is ignored, with a console warning.
   * @returns The same shape as the one-argument `submitTx`.
   */
  submitTx(txCborBytes: Uint8Array, debugScripts: { [key: string]: string }): SubmitResult;
  /**
   * The whole UTxO set in a single CBOR map: keys are transaction inputs (a
   * `[transactionHash, outputIndex]` pair), values are transaction outputs, as in the Cardano
   * ledger CDDL. `getAllUtxos` returns the same data instead as one small map per UTxO.
   */
  getUtxosCbor(): Uint8Array;
  /**
   * The UTxOs that sit at one address.
   *
   * @param addressBech32 The address in bech32 form, for example `addr_test1...`.
   * @returns One CBOR map per UTxO, each holding exactly one input-to-output entry, so a single UTxO can be decoded and passed around on its own.
   */
  getUtxosForAddress(addressBech32: string): Uint8Array[];
  /**
   * Every UTxO in the ledger.
   *
   * @returns One CBOR map per UTxO, each holding exactly one input-to-output entry. Use `getUtxosCbor` for the whole set in one map instead.
   */
  getAllUtxos(): Uint8Array[];
  /**
   * The reward balance of a script stake credential. Key (pub-key) credentials are not supported
   * here; read those with `getDelegation`, which takes any credential.
   *
   * @param scriptHashHex Hex-encoded 28-byte script hash.
   * @returns The balance in lovelace, or `null` if that credential is not registered.
   */
  getStakeReward(scriptHashHex: string): bigint | null;
  /**
   * Moves the clock to an absolute slot, forwards or backwards. Only validity intervals and
   * time-aware scripts see the difference; no blocks are produced in between and no rewards are
   * paid out. A fractional value is truncated.
   */
  setSlot(slot: number): void;
  /** The current slot number of the emulator. */
  getSlot(): number;
  /** Advance the current slot by `n` slots. */
  tick(n: number): void;
  /**
   * Whether a transaction with this hash was accepted by this emulator.
   *
   * @param txHashBytes The raw 32 bytes of the transaction hash, not a hex string. (`getStakeReward` takes hex; this one does not.)
   */
  hasTx(txHashBytes: Uint8Array): boolean;
  /**
   * The pool a stake credential delegates to, and its reward balance.
   *
   * @param stakeCredentialCbor The credential itself, CBOR-encoded: `[0, keyHash]` for a key credential or `[1, scriptHash]` for a script credential, the `stake_credential` of the Cardano ledger CDDL. The result is a plain object, not CBOR.
   * @returns `poolId` is `null` when the credential delegates to no pool. `rewards` is `0n` both for a registered credential with no rewards and for one that was never registered, so use `getStakeReward` when you need to tell the two apart.
   */
  getDelegation(stakeCredentialCbor: Uint8Array): DelegationInfo;
  /**
   * Looks a datum up by its hash, across the datums seeded into this emulator and the ones
   * witnessed by accepted transactions.
   *
   * @param datumHashBytes The raw 32 bytes of the datum hash, not a hex string.
   * @returns The datum as CBOR, or `null` if this emulator has never seen it.
   */
  getDatum(datumHashBytes: Uint8Array): Uint8Array | null;
  /**
   * An independent copy of the whole ledger state: UTxOs, registrations and rewards, the datum
   * store, the accepted transactions, and the current slot. The copy and the original evolve
   * separately from then on, so one expensive setup can branch into several test scenarios
   * without being rebuilt.
   */
  snapshot(): Emulator;
  /**
   * Creates an emulator seeded with a full starting ledger state: UTxOs, and optionally stake
   * credentials, stake pools, DReps and datums. Unlike the constructor, this takes both key and
   * script stake credentials, and takes hashes as hex rather than CBOR.
   *
   * @param state The starting state. Every field except `utxos` may be left out.
   * @param slotConfig Slot arithmetic for the emulated network.
   */
  static withState(state: EmulatorInitialState, slotConfig: SlotConfig): Emulator;
  /**
   * Creates an emulator whose ledger holds one output per address, each carrying only ada. This
   * is the quickest way to get a funded wallet or two for a test.
   *
   * @param addressesBech32 The addresses to fund, in bech32 form.
   * @param slotConfig Slot arithmetic for the emulated network.
   * @param lovelacePerAddress Lovelace in each output. Defaults to `10_000_000_000n`, that is 10 000 ada.
   */
  static withAddresses(addressesBech32: readonly string[], slotConfig: SlotConfig, lovelacePerAddress?: bigint): Emulator;
}

/** Ledger state to seed an emulator with, passed to `Emulator.withState`. Only `utxos` is required. */
export interface EmulatorInitialState {
  /**
   * The starting UTxO set as CBOR: a map from transaction input (a
   * `[transactionHash, outputIndex]` pair) to transaction output, as in the Cardano ledger CDDL.
   */
  readonly utxos: Uint8Array;
  /**
   * Stake credentials that count as already registered, with their reward balances and, if you
   * want, the pool each delegates to.
   */
  readonly stakeRegistrations?: readonly StakeRegistration[];
  /** Stake pools that count as already registered, so transactions may delegate to them. */
  readonly poolRegistrations?: readonly PoolRegistration[];
  /** DReps that count as already registered, so transactions may delegate votes to them. */
  readonly drepRegistrations?: readonly DRepRegistration[];
  /**
   * Datums to put in the emulator's datum store, where `getDatum` looks them up by hash. The
   * store is only a lookup table: every accepted transaction adds the datums it witnesses to it,
   * and validation still requires a transaction to carry the datums it needs.
   */
  readonly datums?: readonly DatumEntry[];
}

/**
 * Outcome of evaluating one Plutus script. Read `isSuccess` first: the two outcomes differ in
 * what `budget` and `logs` mean.
 */
export class EvaluationResult {
  constructor(isSuccess: boolean, budget: ExUnits, logs: readonly string[], profileJson?: string);
  readonly isSuccess: boolean;
  /**
   * Units the machine spent. On failure this is what was spent before the script failed, and
   * zero when the script could not be decoded at all.
   */
  readonly budget: ExUnits;
  /**
   * Trace output the script emitted, oldest first. On failure the failure message is
   * prepended, so `logs[0]` is the error and the traces follow it.
   */
  readonly logs: string[];
  /**
   * Profiling data as JSON; `undefined` unless the script was evaluated with profiling (see
   * {@link evaluateScriptProfile}).
   */
  readonly profileJson?: string;
}

/**
 * Execution units: what a script costs to run, in abstract machine memory and steps. A
 * transaction pays a fee for the units its scripts declare, and the ledger rejects it if a
 * script goes over what it declared.
 */
export class ExUnits {
  constructor(memory: bigint, steps: bigint);
  readonly memory: bigint;
  readonly steps: bigint;
}

/**
 * Thrown by `evalPlutusScripts` when a Plutus script fails to evaluate. Carries the failure
 * message and the script's trace logs. Note: this is a plain object (not a subclass of
 * `Error`), so check it by shape or name rather than `instanceof Error`.
 */
export class PlutusScriptEvaluationError {
  constructor(message: string, logs: readonly string[]);
  readonly message: string;
  readonly logs: string[];
}

/** Pool registration entry for `EmulatorInitialState`. */
export interface PoolRegistration {
  /**
   * The pool's parameters, as one CBOR-encoded Cardano certificate: the whole 10-element
   * `pool_registration` array, tag `3` first, then operator key hash, VRF key hash, pledge,
   * cost, margin, reward account, owners, relays and metadata. The bare parameter list without
   * the certificate tag is rejected.
   */
  readonly params: Uint8Array;
}

/**
 * One redeemer of a transaction, together with the execution budget its script really used.
 * `tag` and `index` together say which script this is, and match the redeemer in the
 * transaction.
 *
 * `tag` is why the script ran: `"Spend"` for a script input, `"Mint"` for a minting policy,
 * `"Cert"` for a certificate, `"Reward"` for a withdrawal, `"Voting"` for a vote, and
 * `"Proposing"` for a governance proposal.
 */
export class RedeemerBudget {
  constructor(tag: "Spend" | "Mint" | "Cert" | "Reward" | "Voting" | "Proposing", index: number, budget: ExUnits);
  readonly tag: "Spend" | "Mint" | "Cert" | "Reward" | "Voting" | "Proposing";
  /**
   * Position within the group named by `tag`, counting from 0: for `"Spend"` it indexes the
   * transaction's inputs in ledger order, for `"Mint"` its minting policies, and so on.
   */
  readonly index: number;
  readonly budget: ExUnits;
}

/**
 * Main API exported by Scalus.
 *
 * @deprecated Use the top-level functions (`evaluateScript`, `evaluateScriptProfile`, `applyDataArgToScript`, `evalPlutusScripts`) instead; this namespace object remains for backwards compatibility.
 */
export const Scalus: {
  /**
   * Applies one argument to a Plutus script and returns the applied script. Use it to bake a
   * parameter into a parameterized validator before you compute its script hash.
   *
   * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
   * @param data The argument in the standard Plutus Data JSON encoding, for example `{"int":42}` or `{"constructor":0,"fields":[{"bytes":"deadbeef"}]}`.
   * @returns The double-CBOR-encoded hex representation of the script with the argument applied.
   */
  applyDataArgToScript(doubleCborHex: string, data: string): string;
  /**
   * Evaluates a Plutus script on its own, with no transaction around it. The script runs on a
   * Plutus V3 machine with the mainnet cost models of the current mainnet protocol major version
   * (11, van Rossem).
   *
   * This never throws. A script that fails, and a script whose hex cannot even be decoded, both
   * come back as a result with `isSuccess: false` and the message in `logs[0]`.
   *
   * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
   * @returns The outcome, with the units spent and the trace logs.
   */
  evaluateScript(doubleCborHex: string): EvaluationResult;
  /**
   * Evaluates a Plutus script with profiling enabled.
   *
   * Same evaluation and same never-throws contract as {@link evaluateScript}, but the result also
   * carries the machine's profiling data as JSON in `profileJson`: cost per source location,
   * cost per builtin, and the transition edges between them.
   *
   * The renderer that turns that JSON into the interactive HTML report is a Scala-side tool
   * (`ProfileFormatter`, in the Scalus library for the JVM). It is deliberately left out of this
   * package to keep the bundle small, so from JavaScript you get the data, not the report.
   *
   * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
   * @returns The outcome, with `profileJson` populated.
   */
  evaluateScriptProfile(doubleCborHex: string): EvaluationResult;
  /**
   * Evaluates every Plutus script a transaction runs, and reports what each one costs. Use it to
   * fill in a transaction's execution units before you balance and submit it.
   *
   * @param txCborBytes CBOR bytes of the transaction whose scripts should run.
   * @param utxoCborBytes CBOR bytes of the UTxO set the scripts see: a CBOR map whose keys are transaction inputs (a `[transactionHash, outputIndex]` pair) and whose values are transaction outputs, as in the Cardano ledger CDDL. It must resolve every input and reference input of the transaction.
   * @param slotConfig Slot arithmetic for the target network, used to turn the transaction's validity interval into the POSIX times the scripts observe.
   * @param costModels One cost model per Plutus language version, indexed by position: `costModels[0]` is Plutus V1, `[1]` is V2, `[2]` is V3. Each inner array holds that version's cost parameters in protocol-parameter order. Give a model for every version the transaction uses; since the position is the version, an earlier version cannot be skipped.
   * @param protocolMajorVersion Cardano protocol major version, which picks the builtin semantics and the costing rules. Defaults to the current mainnet version, 11 (van Rossem).
   * @returns One entry per redeemer of the transaction, carrying the units that redeemer's script spent.
   * @throws PlutusScriptEvaluationError if a script fails; it carries the failure message and that script's trace logs. Only script failures are reported this way: malformed transaction or UTxO CBOR surfaces as an ordinary error instead.
   */
  evalPlutusScripts(txCborBytes: Uint8Array, utxoCborBytes: Uint8Array, slotConfig: SlotConfig, costModels: readonly (readonly number[])[], protocolMajorVersion?: number): RedeemerBudget[];
};

/**
 * Slot and epoch configuration for a Cardano network.
 *
 * Encodes the linear (post-Byron) era as an anchor point: slot `zeroSlot` starts at `zeroTime`
 * (POSIX milliseconds) and falls at the beginning of epoch `zeroEpoch`; slots are `slotLength`
 * milliseconds long and epochs are `epochLength` slots long.
 */
export class SlotConfig {
  constructor(zeroTime: number, zeroSlot: number, slotLength: number, epochLength?: number, zeroEpoch?: number);
  /** POSIX time in milliseconds at which slot `zeroSlot` starts. */
  readonly zeroTime: number;
  /** The slot this config is anchored at: the first slot of the linear (post-Byron) era. */
  readonly zeroSlot: number;
  /** Slot length in milliseconds. */
  readonly slotLength: number;
  /** Epoch length in slots. */
  readonly epochLength: number;
  /** Number of the epoch that begins at `zeroSlot`. */
  readonly zeroEpoch: number;
  /** POSIX time in milliseconds at which the given slot starts. */
  slotToTime(slot: number): number;
  /**
   * The slot that contains the given POSIX time in milliseconds.
   *
   * The result is fractional whenever the time does not land exactly on a slot boundary, and
   * with one-second slots `timeToSlot(Date.now())` almost never does. Round it yourself before
   * you use it as a slot number, for example with `Math.floor`; `Emulator.setSlot` truncates a
   * fractional value rather than rejecting it.
   */
  timeToSlot(time: number): number;
  /** Epoch containing the given slot. Slots before `zeroSlot` are clamped to `zeroEpoch`. */
  epochOf(slot: number): number;
  /** First slot of the given epoch (for epochs >= `zeroEpoch`). */
  firstSlotOfEpoch(epoch: number): number;
  /** Mainnet slot configuration starting at Shelley era (slot 4492800 = start of epoch 208) */
  static readonly mainnet: SlotConfig;
  /** Preview testnet slot configuration starting at Shelley era (1-day epochs) */
  static readonly preview: SlotConfig;
  /** Preprod testnet slot configuration (slot 86400 = start of epoch 4, after 4 Byron epochs) */
  static readonly preprod: SlotConfig;
}

/** Stake registration entry for `EmulatorInitialState`. */
export interface StakeRegistration {
  /** Credential type: "key" for pub key hash, "script" for script hash. */
  readonly credentialType: "key" | "script";
  /** Hex-encoded 28-byte credential hash */
  readonly credentialHash: string;
  /** Starting reward balance in lovelace. */
  readonly rewards: bigint;
  /**
   * Hex-encoded 28-byte key hash of the pool this credential delegates to. Leave it out for a
   * credential that is registered but delegates to nothing.
   */
  readonly delegatedTo?: string;
}

/**
 * Result of `Emulator.submitTx`. Read `isSuccess` first: the other three fields are each present
 * for one outcome only.
 */
export interface SubmitResult {
  readonly isSuccess: boolean;
  /** Transaction hash hex; present on success. */
  readonly txHash?: string;
  /** Error message; present on failure. */
  readonly error?: string;
  /** Script trace logs; present on script failure. */
  readonly logs?: string[];
}

/**
 * Applies one argument to a Plutus script and returns the applied script. Use it to bake a
 * parameter into a parameterized validator before you compute its script hash.
 *
 * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
 * @param data The argument in the standard Plutus Data JSON encoding, for example `{"int":42}` or `{"constructor":0,"fields":[{"bytes":"deadbeef"}]}`.
 * @returns The double-CBOR-encoded hex representation of the script with the argument applied.
 */
export function applyDataArgToScript(doubleCborHex: string, data: string): string;

/**
 * Evaluates every Plutus script a transaction runs, and reports what each one costs. Use it to
 * fill in a transaction's execution units before you balance and submit it.
 *
 * @param txCborBytes CBOR bytes of the transaction whose scripts should run.
 * @param utxoCborBytes CBOR bytes of the UTxO set the scripts see: a CBOR map whose keys are transaction inputs (a `[transactionHash, outputIndex]` pair) and whose values are transaction outputs, as in the Cardano ledger CDDL. It must resolve every input and reference input of the transaction.
 * @param slotConfig Slot arithmetic for the target network, used to turn the transaction's validity interval into the POSIX times the scripts observe.
 * @param costModels One cost model per Plutus language version, indexed by position: `costModels[0]` is Plutus V1, `[1]` is V2, `[2]` is V3. Each inner array holds that version's cost parameters in protocol-parameter order. Give a model for every version the transaction uses; since the position is the version, an earlier version cannot be skipped.
 * @param protocolMajorVersion Cardano protocol major version, which picks the builtin semantics and the costing rules. Defaults to the current mainnet version, 11 (van Rossem).
 * @returns One entry per redeemer of the transaction, carrying the units that redeemer's script spent.
 * @throws PlutusScriptEvaluationError if a script fails; it carries the failure message and that script's trace logs. Only script failures are reported this way: malformed transaction or UTxO CBOR surfaces as an ordinary error instead.
 */
export function evalPlutusScripts(txCborBytes: Uint8Array, utxoCborBytes: Uint8Array, slotConfig: SlotConfig, costModels: readonly (readonly number[])[], protocolMajorVersion?: number): RedeemerBudget[];

/**
 * Evaluates a Plutus script on its own, with no transaction around it. The script runs on a
 * Plutus V3 machine with the mainnet cost models of the current mainnet protocol major version
 * (11, van Rossem).
 *
 * This never throws. A script that fails, and a script whose hex cannot even be decoded, both
 * come back as a result with `isSuccess: false` and the message in `logs[0]`.
 *
 * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
 * @returns The outcome, with the units spent and the trace logs.
 */
export function evaluateScript(doubleCborHex: string): EvaluationResult;

/**
 * Evaluates a Plutus script with profiling enabled.
 *
 * Same evaluation and same never-throws contract as {@link evaluateScript}, but the result also
 * carries the machine's profiling data as JSON in `profileJson`: cost per source location,
 * cost per builtin, and the transition edges between them.
 *
 * The renderer that turns that JSON into the interactive HTML report is a Scala-side tool
 * (`ProfileFormatter`, in the Scalus library for the JVM). It is deliberately left out of this
 * package to keep the bundle small, so from JavaScript you get the data, not the report.
 *
 * @param doubleCborHex The double-CBOR-encoded hex representation of the Plutus script.
 * @returns The outcome, with `profileJson` populated.
 */
export function evaluateScriptProfile(doubleCborHex: string): EvaluationResult;

/** @deprecated Use RedeemerBudget instead. */
export { RedeemerBudget as Redeemer };
/** @deprecated Use EvaluationResult instead. */
export { EvaluationResult as Result };
