package scalus.tsexport

/** Renders a [[TsModule]] as deterministic `.d.ts` text. */
object Emitter {

    private val header = "// Generated by scalus-ts-exporter. DO NOT EDIT."

    def render(t: TsType): String = render(t, readonlyArrays = false)

    /** @param readonlyArrays
      *   render arrays as `readonly T[]`. Set in INPUT positions - parameters and the properties of
      *   the generated interfaces, which callers fill in - so a caller holding a `ReadonlyArray`
      *   can pass it. Return types and class properties stay mutable: callers own what they are
      *   handed and do `getAllUtxos().map(...).push(...)`.
      */
    private def render(t: TsType, readonlyArrays: Boolean): String = t match
        case TsType.Named(n)  => n
        case TsType.Union(ms) => ms.map(render(_, readonlyArrays)).mkString(" | ")
        // `&` binds tighter than `|`, so only union and function members need parentheses
        case TsType.Intersect(ms) =>
            ms.map {
                case m @ (TsType.Union(_) | TsType.Func(_, _)) =>
                    s"(${render(m, readonlyArrays)})"
                case m => render(m, readonlyArrays)
            }.mkString(" & ")
        case TsType.Arr(elem) =>
            val inner = render(elem, readonlyArrays)
            val parenthesized = elem match
                case TsType.Union(_) | TsType.Func(_, _) | TsType.Intersect(_) => s"($inner)"
                // `readonly (readonly T[])[]`: the inner `readonly` needs the parentheses
                case TsType.Arr(_) if readonlyArrays => s"($inner)"
                case _                               => inner
            if readonlyArrays then s"readonly $parenthesized[]" else s"$parenthesized[]"
        // Variance flips across a function boundary: WE call the callback, so its parameters
        // are values we hand out (mutable), while its result is something we take in. Forcing
        // `readonly` on them rejected the natural `(xs: string[]) => void` a consumer writes.
        case TsType.Func(ps, ret) =>
            s"(${ps.map(renderParam(_, !readonlyArrays)).mkString(", ")}) => " +
                render(ret, readonlyArrays)
        case TsType.Index(v)       => s"{ [key: string]: ${render(v, readonlyArrays)} }"
        case TsType.Generic(n, as) => s"$n<${as.map(render(_, readonlyArrays)).mkString(", ")}>"
        case TsType.Verbatim(text) => text

    private def renderParam(p: TsParam, readonlyArrays: Boolean = true): String =
        s"${p.name}${if p.optional then "?" else ""}: ${render(p.tpe, readonlyArrays)}"

    private def renderTypeParam(tp: TsTypeParam): String =
        tp.bound.fold(tp.name)(b => s"${tp.name} extends ${render(b)}")

    /** `""` for no type parameters, otherwise `<A, B extends object>`. */
    private def renderTypeParams(tps: List[TsTypeParam]): String =
        if tps.isEmpty then "" else tps.map(renderTypeParam).mkString("<", ", ", ">")

    private def renderSignature(o: TsOverload): String =
        s"${renderTypeParams(o.typeParams)}(${o.params.map(renderParam(_)).mkString(", ")}): " +
            render(o.ret)

    private def renderDoc(doc: TsDoc, indent: String): List[String] =
        if doc.lines.sizeIs == 1 then List(s"$indent/** ${doc.lines.head} */")
        else
            s"$indent/**" :: doc.lines.map(l => s"$indent * $l".stripTrailing) ::: List(
              s"$indent */"
            )

    private def docLines(doc: Option[TsDoc], indent: String): List[String] =
        doc.fold(Nil)(renderDoc(_, indent))

    private def renderMember(m: TsMember, indent: String, inputPos: Boolean): List[String] =
        m match
            case TsMember.Ctor(overloads, doc) =>
                docLines(doc, indent) ++ overloads.map(ps =>
                    s"${indent}constructor(${ps.map(renderParam(_)).mkString(", ")});"
                )
            case TsMember.Method(name, overloads, static) =>
                val prefix = if static then "static " else ""
                overloads.flatMap(o =>
                    docLines(o.doc, indent) :+ s"$indent$prefix$name${renderSignature(o)};"
                )
            case TsMember.Property(name, tpe, readonly, optional, static, doc) =>
                val prefix =
                    (if static then "static " else "") + (if readonly then "readonly " else "")
                val opt = if optional then "?" else ""
                docLines(doc, indent) :+
                    s"$indent$prefix$name$opt: ${render(tpe, readonlyArrays = inputPos)};"

    private def renderBody(
        members: List[TsMember],
        indent: String,
        inputPos: Boolean = false
    ): List[String] =
        members.flatMap(renderMember(_, indent, inputPos))

    private def renderDecl(d: TsDecl): List[String] = d match
        case TsDecl.Cls(name, typeParams, superClass, members, doc, _) =>
            val extendsClause = superClass.fold("")(s => s" extends $s")
            docLines(doc, "") ++
                (s"export class $name${renderTypeParams(typeParams)}$extendsClause {" ::
                    renderBody(members, "  ") ::: List("}"))
        case TsDecl.Iface(name, typeParams, members, doc, inputOnly) =>
            docLines(doc, "") ++
                (s"export interface $name${renderTypeParams(typeParams)} {" ::
                    renderBody(members, "  ", inputPos = inputOnly) ::: List("}"))
        case TsDecl.Fun(name, overloads, _) =>
            overloads.flatMap(o =>
                docLines(o.doc, "") :+ s"export function $name${renderSignature(o)};"
            )
        case TsDecl.ConstObj(name, members, doc) =>
            docLines(doc, "") ++
                (s"export const $name: {" :: renderBody(members, "  ") ::: List("};"))

    def emit(module: TsModule): String = {
        val sorted = module.decls.sortBy(_.name)
        val aliases = module.decls
            .collect {
                case c: TsDecl.Cls => c.deprecatedAliases.map(a => (a, c.name))
                case f: TsDecl.Fun => f.deprecatedAliases.map(a => (a, f.name))
            }
            .flatten
            .sortBy(_._1)
            .flatMap { case (alias, canonical) =>
                List(
                  s"/** @deprecated Use $canonical instead. */",
                  s"export { $canonical as $alias };"
                )
            }
        val blocks = sorted.map(renderDecl) ++ (if aliases.isEmpty then Nil else List(aliases))
        (List(header) :: blocks).map(_.mkString("\n")).mkString("\n\n") + "\n"
    }
}
