package scalus.lean

import org.scalatest.funsuite.AnyFunSuite
import scalus.utils.Hex

import java.nio.file.{Files, Path}

class ExportUplcTest extends AnyFunSuite {

    private def withTempDir[A](f: Path => A): A = {
        val dir = Files.createTempDirectory("lean-export-test")
        try f(dir)
        finally {
            Files.walk(dir).sorted(java.util.Comparator.reverseOrder()).forEach(Files.delete)
        }
    }

    test("writes one flat file per target plus Targets.lean") {
        withTempDir { dir =>
            ExportUplc.write(dir)
            ProofTargets.all.foreach { t =>
                assert(Files.exists(dir.resolve(s"${t.name}.flat")), s"missing ${t.name}.flat")
            }
            assert(Files.exists(dir.resolve("Targets.lean")))
        }
    }

    test("flat files are lowercase hex that round-trips to the original program") {
        withTempDir { dir =>
            ExportUplc.write(dir)
            ProofTargets.all.foreach { t =>
                val hex = Files.readString(dir.resolve(s"${t.name}.flat"))
                assert(hex.matches("[0-9a-f]+"), s"${t.name}.flat is not lowercase hex")
                assert(
                  Hex.hexToBytes(hex).sameElements(t.program.cborEncoded),
                  s"${t.name} mismatch"
                )
            }
        }
    }

    test("Targets.lean has an import and a native_decide check per sample") {
        withTempDir { dir =>
            ExportUplc.write(dir)
            val lean = Files.readString(dir.resolve("Targets.lean"))
            ProofTargets.all.foreach { t =>
                assert(
                  lean.contains(
                    s"""#import_uplc ${t.leanName} PlutusV3 single_cbor_hex "ScalusProofs/Generated/${t.name}.flat""""
                  ),
                  s"missing import for ${t.name}"
                )
            }
            val expectedChecks = ProofTargets.all.map(_.samples.size).sum
            assert(lean.split("native_decide").length - 1 == expectedChecks)
            assert(lean.contains("namespace ScalusProofs.Generated"))
            assert(lean.contains("Generated by `sbt exportLeanUplc`"))
        }
    }

    test("export is deterministic") {
        withTempDir { a =>
            withTempDir { b =>
                ExportUplc.write(a)
                ExportUplc.write(b)
                ProofTargets.all.foreach { t =>
                    val fa = Files.readString(a.resolve(s"${t.name}.flat"))
                    val fb = Files.readString(b.resolve(s"${t.name}.flat"))
                    assert(fa == fb, s"${t.name}.flat is not deterministic")
                }
                assert(
                  Files.readString(a.resolve("Targets.lean")) == Files.readString(
                    b.resolve("Targets.lean")
                  )
                )
            }
        }
    }
}
