package scalus.lean

import scalus.utils.Hex

import java.nio.file.{Files, Path}

/** Writes the compiled UPLC of every [[ProofTargets.all]] entry in the form the Lean proof suite
  * consumes, plus a generated Lean file of imports and differential checks.
  *
  * The generated output is committed to git, so the Lean half of the module builds without a JVM.
  * `exportLeanUplc` regenerates it; CI fails if the result differs from what is committed.
  */
object ExportUplc {

    /** Budget used only by the generated differential checks. Large enough for every target;
      * `runSteps` short-circuits once the machine halts, so an oversized value costs nothing. Proof
      * budgets are NOT this value: they are calibrated per property file.
      */
    private val guardBudget = 20000

    private def header: String =
        s"""-- Generated by `sbt exportLeanUplc`. Do not edit by hand.
           |--
           |-- Each `example` below asserts that the Lean CEK machine produces the value Scalus's
           |-- own JVM CEK produced for the same arguments, so the two implementations are checked
           |-- against each other on every build. A failing check most often means the compiled
           |-- program changed, not that the Lean model is wrong.
           |import ScalusProofs.Prelude
           |
           |namespace ScalusProofs.Generated
           |open PlutusCore.Integer (Integer)
           |open ScalusProofs.Prelude
           |
           |set_option warn.sorry false
           |""".stripMargin

    private def renderArgs(args: Seq[BigInt]): String =
        args.map(a => if a < 0 then s"($a)" else a.toString).mkString("[", ", ", "]")

    private def renderExpected(v: BigInt): String = if v < 0 then s"($v)" else v.toString

    private def renderTarget(t: ProofTarget): String = {
        val imp =
            s"""#import_uplc ${t.leanName} PlutusV3 single_cbor_hex "ScalusProofs/Generated/${t.name}.flat""""
        val checks = t.samples.zipWithIndex.map { case ((args, expected), i) =>
            s"""example : runInts ${t.leanName} ${renderArgs(args)} $guardBudget """ +
                s"""= some ${renderExpected(expected)} := by native_decide"""
        }
        (imp +: checks).mkString("\n") + "\n"
    }

    /** Writes every target into `dir`. Returns the paths written. */
    def write(dir: Path): Seq[Path] = {
        Files.createDirectories(dir)
        val flats = ProofTargets.all.map { t =>
            val p = dir.resolve(s"${t.name}.flat")
            Files.writeString(p, Hex.bytesToHex(t.program.cborEncoded).toLowerCase)
            p
        }
        val body = ProofTargets.all.map(renderTarget).mkString("\n")
        val lean = dir.resolve("Targets.lean")
        Files.writeString(lean, s"$header\n$body\nend ScalusProofs.Generated\n")
        flats :+ lean
    }

    def main(args: Array[String]): Unit = {
        require(args.nonEmpty, "usage: ExportUplc <outputDir>")
        val written = write(Path.of(args(0)))
        written.foreach(p => println(s"wrote $p"))
        println(s"${written.size} files, ${ProofTargets.all.size} targets")
    }
}
