#!/usr/bin/env python3
"""Regenerate libsodium-verdicts.tsv: Ed25519 vectors with libsodium's verdict.

Usage: generate_libsodium_verdicts.py <path to libsodium.dylib or .so> > libsodium-verdicts.tsv

The Cardano node verifies with libsodium 1.0.18 code (IOG fork dbb48cce). Later releases up to
1.0.22 give the same verdicts on these vectors.
"""
import ctypes
import json
import sys
import urllib.request

CCTV = ("https://raw.githubusercontent.com/C2SP/CCTV/"
        "50a8ecf2a220f4c8bdc4f085789b8e85c26829e7/ed25519/ed25519vectors.json")
SPECCHECK = ("https://raw.githubusercontent.com/novifinancial/ed25519-speccheck/"
             "65519336fda78a3d016e947df6d82848aca0c9da/cases.json")

RFC8032_PK = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"
REPRO_MSG = b"scalus ed25519 repro".hex()
# From the bug report: RFC 8032 test 1, the same with its last byte flipped, then two signatures by
# the RFC 8032 test 1 key with R = identity and with R carrying an order-8 component.
ISSUE = [
    ("rfc8032-test1", RFC8032_PK, "",
     "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b"),
    ("rfc8032-test1-flipped", RFC8032_PK, "",
     "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100a"),
    ("r-identity", RFC8032_PK, REPRO_MSG,
     "0100000000000000000000000000000000000000000000000000000000000000943d85c895b02c2a57afbba668e5641527063f11dff33f5a6d2de65e6b45f00e"),
    ("r-order8-component", RFC8032_PK, REPRO_MSG,
     "c37aece30145ac8d15385f30be8d9e303d770583f5e5008c47125818b45a51c4033e7c23808064f3eb008b4907e907ae6ed15ffba46f98cdf96408f67988a002"),
]


def main():
    lib = ctypes.CDLL(sys.argv[1])
    assert lib.sodium_init() >= 0
    lib.sodium_version_string.restype = ctypes.c_char_p

    def verify(pk, msg, sig):
        return lib.crypto_sign_ed25519_verify_detached(
            sig, msg, ctypes.c_ulonglong(len(msg)), pk) == 0

    rows = [("cctv", str(v["number"]), v["key"], v["msg"].encode().hex(), v["sig"])
            for v in json.load(urllib.request.urlopen(CCTV))]
    rows += [("speccheck", str(i), v["pub_key"], v["message"], v["signature"])
             for i, v in enumerate(json.load(urllib.request.urlopen(SPECCHECK)))]
    rows += [("issue", name, pk, msg, sig) for name, pk, msg, sig in ISSUE]

    verdicts = [verify(bytes.fromhex(row[2]), bytes.fromhex(row[3]), bytes.fromhex(row[4]))
                for row in rows]

    print(f"# Generated by generate_libsodium_verdicts.py with libsodium "
          f"{lib.sodium_version_string().decode()} crypto_sign_ed25519_verify_detached")
    print(f"# CCTV {CCTV}")
    print(f"# speccheck {SPECCHECK}")
    print(f"# rows={len(rows)} accepts={sum(verdicts)}")
    print("# source\tid\tpk\tmsg\tsig\tverdict")
    for row, ok in zip(rows, verdicts):
        print("\t".join(row + ("accept" if ok else "reject",)))


if __name__ == "__main__":
    main()
