export default {
  index: '',
  'get-started': 'Getting Started',
  'multiplatform': 'Multiplatform',
  'language-guide': 'Language Guide',
  'smart-contracts': 'Smart Contracts',
  'smart-contract-optimisations': 'Advanced Optimisations',
  'transactions': 'Transactions',
  testing: 'Testing',
  'design-patterns': 'Design Patterns',
  'advanced-data-structures': 'Advanced Data Structures',
  security: 'Security',
  'dapp-development': 'DApp Development',
  ledger: 'Ledger Framework',
  catalyst: 'Catalyst',
}
