export default {
  index: '',
  'get-started': '',
  'multiplatform': 'Multiplatform',
  'onboarding': '',
  'language-guide': 'Language Guide',
  'smart-contracts': 'Smart Contracts',
  'transactions': 'Transactions',
  testing: 'Testing',
  'design-patterns': 'Design Patterns',
  'offchain-applications': 'Offchain Applications',
  ledger: 'Ledger Framework',
  learning: '',
  catalyst: 'Catalyst',
}
