package scalus.cardano.node

import io.bullet.borer.Cbor
import org.scalatest.funsuite.AnyFunSuite
import scalus.cardano.address.{Network, StakeAddress, StakePayload}
import scalus.cardano.ledger.*
import scalus.cardano.txbuilder.{ScriptSource, TwoArgumentPlutusScriptWitness, TxBuilder}
import scalus.testing.kit.Party.Alice
import scalus.uplc.{DefaultFun, Term}
import scalus.uplc.Term.*
import scalus.uplc.TermDSL.given
import scalus.uplc.builtin.{platform, ByteString, Data}

// TermDSL lifts a DefaultFun into a Term implicitly, which is what makes the UPLC below readable.
import scala.language.implicitConversions

/** Guards `__tests__/fixtures.ts` against the code that produced it.
  *
  * The npm differential test evaluates one transaction with two evaluators and compares the
  * budgets. That is only worth anything if the transaction really exercises the layer an evaluator
  * adapter drives — script-context construction, redeemer indexing, cost-model selection — so
  * [[contextSensitiveScript]] is written to make its own cost depend on the redeemer, on the
  * transaction's inputs and on the script purpose. Get any of the three wrong and the budget moves.
  *
  * The fixture is still generated by hand (run this, copy the two hex strings), but the assertions
  * below make it a guard rather than a printout: change the fee model, `Party.Alice`'s key or the
  * script, and this fails naming what to re-copy — instead of the committed fixture going quietly
  * stale while every test that reads it keeps passing.
  */
class DifferentialFixtureGenTest extends AnyFunSuite {

    given testEnv: CardanoInfo = CardanoInfo.mainnet

    /** The redeemer the committed fixture carries. Its value is the loop count the script runs, so
      * it is visible in the pinned budget.
      */
    private val fixtureRedeemer: BigInt = 5

    /** A PlutusV3 script whose execution budget depends on what it is handed.
      *
      * Written as raw UPLC rather than compiled from Scala on purpose: the fixture pins the
      * transaction's bytes, and the Scalus compiler's output legitimately differs between the Scala
      * versions this repo cross-builds on, which would make the pin fail on one of them. A hand
      * written term is the same bytes everywhere.
      *
      * It reads the `ScriptContext` (`Constr 0 [txInfo, redeemer, scriptInfo]`), takes the redeemer
      * as an integer, counts the transaction's inputs (`TxInfo` field 0) and takes the script
      * purpose's constructor tag (`RewardingScript` is 2), then counts down from their sum. So the
      * budget is a function of all three: an adapter that builds the context from the wrong inputs,
      * passes the wrong redeemer, or reports the wrong purpose produces a different budget, and one
      * that hands over something that is not a `ScriptContext` at all fails outright.
      */
    private val contextSensitiveScript: Script.PlutusV3 = {
        import DefaultFun.*

        // λself. λxs. λacc. force (ifThenElse (nullList xs) (delay acc)
        //                                    (delay (self self (tailList xs) (addInteger acc 1))))
        val lengthOf = λ("self", "xs", "acc")(
          !(!IfThenElse $ (!NullList $ vr"xs")
              $ ~vr"acc"
              $ ~(vr"self" $ vr"self" $ (!TailList $ vr"xs") $ (AddInteger $ vr"acc" $ 1.asTerm)))
        )

        // λself. λn. force (ifThenElse (lessThanEqualsInteger n 0) (delay ())
        //                              (delay (self self (subtractInteger n 1))))
        val countdown = λ("self", "n")(
          !(!IfThenElse $ (LessThanEqualsInteger $ vr"n" $ 0.asTerm)
              $ ~().asTerm
              $ ~(vr"self" $ vr"self" $ (SubtractInteger $ vr"n" $ 1.asTerm)))
        )

        /** `f f x …` — the self-application fixpoint, with `f` bound once so the helper term
          * appears in the script exactly once.
          */
        def fix(helper: Term, args: Term*): Term =
            λ("f")(args.foldLeft(vr"f" $ vr"f")(_ $ _)) $ helper

        val ctxFields = !(!SndPair) $ (UnConstrData $ vr"ctx")
        val txInfo = !HeadList $ vr"fields"
        val afterTxInfo = !TailList $ vr"fields"
        val redeemer = !HeadList $ afterTxInfo
        val scriptInfo = !HeadList $ (!TailList $ afterTxInfo)

        val inputs = UnListData $ (!HeadList $ (!(!SndPair) $ (UnConstrData $ txInfo)))
        val purposeTag = !(!FstPair) $ (UnConstrData $ scriptInfo)

        val term = λ("ctx")(
          λ("fields")(
            fix(
              countdown,
              AddInteger
                  $ (UnIData $ redeemer)
                  $ (AddInteger $ fix(lengthOf, inputs, 0.asTerm) $ purposeTag)
            )
          ) $ ctxFields
        )

        Script.PlutusV3(term.plutusV3.cborByteString)
    }

    private val genesisHash = TransactionHash.fromByteString(ByteString.fromHex("0" * 64))
    private val alice = Alice.address(Network.Mainnet)
    private val scriptHash = contextSensitiveScript.scriptHash
    private val stakeCred = Credential.ScriptHash(scriptHash)
    private val stakeAddress = StakeAddress(Network.Mainnet, StakePayload.Script(scriptHash))

    private val initialUtxos: Utxos = Map(
      Input(genesisHash, 0) -> Output(alice, Value.ada(5000))
    )

    /** A zero-value withdrawal from a script-controlled stake address: the smallest transaction
      * that runs a PlutusV3 script, and one both MeshJS and lucid-evolution can be handed.
      */
    private def withdrawalTx(redeemer: BigInt): Transaction = {
        val emulator = Emulator.withRegisteredStakeCredentials(
          initialUtxos = initialUtxos,
          initialStakeRewards = Map(stakeCred -> Coin.zero)
        )
        val witness = TwoArgumentPlutusScriptWitness(
          ScriptSource.PlutusScriptValue(contextSensitiveScript),
          Data.I(redeemer)
        )
        val tx = TxBuilder(testEnv)
            .withdrawRewards(stakeAddress, Coin.zero, witness)
            .complete(initialUtxos, alice)
            .sign(Alice.signer)
            .transaction
        assert(emulator.submitSync(tx).isRight, s"the fixture transaction must be valid: $tx")
        tx
    }

    /** The execution budget the builder computed for the transaction's single redeemer. */
    private def budgetOf(tx: Transaction): ExUnits = {
        val redeemers = tx.witnessSet.redeemers.map(_.value.toMap).getOrElse(Map.empty)
        assert(redeemers.size == 1, s"expected exactly one redeemer, got ${redeemers.size}")
        redeemers.head._2._2
    }

    // `& 0xff` is load-bearing: Byte is signed, and "%02x".format widens it to Int with sign
    // extension, so -1 renders as "ffffffff" rather than "ff".
    private def hex(bytes: Array[Byte]): String = bytes.map(b => "%02x".format(b & 0xff)).mkString

    private val fixturesPath = "scalus-cardano-ledger/js/src/main/npm/__tests__/fixtures.ts"

    /** The value of one `export const <name> = "…" + "…";` in the fixture file.
      *
      * The hex strings are committed as several quoted chunks joined with `+` so the file stays
      * readable, so reading one back means gluing the quoted parts together again.
      */
    private def fixtureConstant(source: String, name: String): String = {
        val marker = s"export const $name ="
        val start = source.indexOf(marker)
        assert(start >= 0, s"$fixturesPath no longer exports `$name`")
        val end = source.indexOf(';', start)
        assert(end > start, s"$fixturesPath: `$name` has no terminating semicolon")
        "\"([^\"]*)\"".r
            .findAllMatchIn(source.substring(start + marker.length, end))
            .map(_.group(1))
            .mkString
    }

    test("the committed npm fixture is the transaction this generator produces") {
        val tx = withdrawalTx(fixtureRedeemer)
        val txHex = hex(tx.toCbor)
        val utxoHex = hex(Cbor.encode(initialUtxos).toByteArray)
        // The script exactly as an SDK takes it: `Script.PlutusV3.script` is already the flat
        // program wrapped in one CBOR bytestring, which is what `applyDoubleCborEncoding` produces
        // and what `PlutusScript.from_cbor_hex` reads. `provider-lucid.test.ts` hands lucid this
        // string, so a hash computed there must equal `contextSensitiveScript.scriptHash`.
        val scriptHex = hex(contextSensitiveScript.script.bytes)
        val budget = budgetOf(tx)

        println(s"FIXTURE_TX_HEX=$txHex")
        println(s"FIXTURE_UTXO_HEX=$utxoHex")
        println(s"FIXTURE_SCRIPT_HEX=$scriptHex")
        println(s"FIXTURE_BUDGET mem=${budget.memory} steps=${budget.steps}")

        val fixtures = new String(platform.readFile(fixturesPath), "UTF-8")

        def regenerate(name: String, value: String): String =
            s"$fixturesPath is stale: its `$name` is not what this generator produces. " +
                s"Re-run this test and copy the printed value into it:\n$value"

        assert(
          fixtureConstant(fixtures, "scriptTxCborHex") == txHex,
          regenerate("scriptTxCborHex", txHex)
        )
        assert(
          fixtureConstant(fixtures, "scriptUtxoCborHex") == utxoHex,
          regenerate("scriptUtxoCborHex", utxoHex)
        )
        assert(
          fixtureConstant(fixtures, "contextSensitiveScriptHex") == scriptHex,
          regenerate("contextSensitiveScriptHex", scriptHex)
        )

        // The npm tests pin this budget in three places (provider-mesh, provider-lucid and the
        // differential); pinning it here too means a change surfaces on the Scala side, in the
        // file that can say what to do about it, rather than only after the bundle is relinked.
        assert(
          budget == ExUnits(memory = 32318, steps = 8_754_898),
          s"the fixture's budget moved to mem=${budget.memory} steps=${budget.steps}; update " +
              "provider-mesh.test.ts, provider-lucid.test.ts and differential.test.ts to match"
        )
    }

    test("the fixture's budget really depends on the redeemer and the script context") {
        // The guard on the guard: if this passes with two different redeemers producing one
        // budget, the fixture script ignores what it is handed and every budget assertion that
        // reads the fixture is vacuous - which is exactly what the previous `alwaysOk` fixture did.
        val withFive = budgetOf(withdrawalTx(5))
        val withNine = budgetOf(withdrawalTx(9))
        assert(
          withFive != withNine,
          s"the script's cost must move with the redeemer, but both cost $withFive"
        )
        assert(withNine.steps > withFive.steps, s"$withNine should cost more than $withFive")
    }
}
