package scalus.testing.conformance

import org.scalatest.Tag
import org.scalatest.funsuite.*
import scalus.testing.conformance.CardanoLedgerVectors.*

/** Cardano Ledger Conformance Test Suite
  *
  * Runs conformance tests from cardano-ledger test vectors to validate Scalus ledger implementation
  * against reference implementation.
  *
  * ==Budget Difference Investigation (December 2025)==
  *
  * Some conformance tests fail with "Out of budget" errors. Investigation revealed:
  *
  * '''Key Finding: Scalus matches current Haskell `uplc` tool exactly.'''
  *
  * Comparison results on identical applied programs:
  * {{{
  * Test vector budget (cardano-ledger):  mem=352394,  cpu=91377951
  * Scalus computed budget:               mem=353696,  cpu=91714333
  * Haskell uplc (v1.56.0.0) budget:      mem=353696,  cpu=91714333
  *
  * Differences:
  *   Scalus vs Test Vector:  mem=+1302, cpu=+336382
  *   Uplc vs Test Vector:    mem=+1302, cpu=+336382
  *   Scalus vs Uplc:         mem=0,     cpu=0        <-- EXACT MATCH
  * }}}
  *
  * '''Root Cause:''' The test vectors were generated by cardano-ledger's test suite (files dated
  * May 15, 2025) with budgets computed at that time. Since then, Plutus cost accounting may have
  * changed slightly, causing both Scalus and current Haskell `uplc` to compute higher budgets than
  * what's stored in the test vectors.
  *
  * '''The constant offset''' (mem=+1302, cpu=+336382) across all failing tests proves this is a
  * systematic difference, not a bug in Scalus.
  *
  * '''Relevant Changes in 2025:'''
  *   - Jan 29, 2025: cardano-ledger PR #4854 "Implement memoization of Plutus script context
  *     computation"
  *   - Various Plutus cost model updates and optimizations throughout 2025
  *
  * '''Conclusion:''' Scalus implementation is correct. The test vectors need to be regenerated with
  * current cardano-ledger to get matching budgets.
  *
  * @see
  *   [[https://github.com/IntersectMBO/cardano-ledger/pull/4854 PR #4854]]
  * @see
  *   [[https://github.com/IntersectMBO/plutus/blob/master/plutus-core/CHANGELOG.md Plutus CHANGELOG]]
  */
class CardanoLedgerConformanceTest extends AnyFunSuite {

    // Test all vectors with UTXO cases
    for vector <- vectorNames().filter(_.contains(".UTXO")) do {
        test("Conformance test vector: " + vector):
            for
                case (x, success, result) <- testVector(vector)
                if success != (result.isSuccess && result.get.isRight)
            do fail(s"[$vector/$x]($success) $result")
    }

    ignore("Debug specific vector") {
        val vector =
            "Conway.Imp.ConwayImpSpec - Version 10.UTXOS.Conway features fail in Plutusdescribe v1 and v2.Unsupported Fields.CurrentTreasuryValue.V1"
        println(s"Debugging vector: $vector")
        print(pprint(testVector(vector)))
    }
}
