package scalus.testing.conformance

import scalus.cardano.ledger.{SlotConfig, Transaction, TransactionInput, TransactionOutput}

import java.security.MessageDigest
import java.util.zip.GZIPInputStream

/** Golden TxInfo translation vectors produced by the real Haskell cardano-ledger.
  *
  * The corpus is `eras/conway/impl/golden/translations.cbor`, generated by
  * `cabal run cardano-ledger-conway:gen-golden` with a fixed seed. Each instance is
  * `(ProtVer, SupportedLanguage, UTxO, Tx, VersionedTxInfo)`, where the last field is the TxInfo
  * the Haskell ledger produced for that transaction.
  *
  * This makes it an oracle that is **independent of our own translator**, which is the whole point:
  * our other script-context tests build the context with `LedgerToPlutusTranslation` and then check
  * it against itself, so any consistently-wrong ordering passes.
  *
  * The corpus is vendored, gzipped, as a test resource so the suite runs without nix. Provenance:
  * {{{
  * https://raw.githubusercontent.com/IntersectMBO/cardano-ledger/
  *   cardano-ledger-conway-1.22.1.0/eras/conway/impl/golden/translations.cbor
  * }}}
  * pinned at the mainnet-deployed tag. [[CorpusSha256]] is checked on every load, so a corrupted or
  * swapped resource fails loudly rather than silently changing what the oracle asserts. A missing
  * corpus is likewise a hard failure, never a skip: an oracle that can quietly not run reproduces
  * the very blindness it exists to remove.
  */
object GoldenTranslationVectors {

    /** sha256 of the pinned corpus. Must match `flake.nix`. A mismatch means the pin moved and
      * every expectation below needs re-diffing against the new corpus.
      */
    val CorpusSha256 = "5d02c08e392f135fa56ed3177d1987ef0d90f8274f9f37d450d4f4d1d4c9cc7a"

    /** Language tags as encoded in the corpus (the `SupportedLanguage` constructor index). */
    val PlutusV1 = 0
    val PlutusV2 = 1
    val PlutusV3 = 2

    /** The environment the corpus was generated under:
      * `fixedEpochInfo (EpochSize 100) (mkSlotLength 1)` and
      * `systemStart = posixSecondsToUTCTime 1684445839000`
      * (`Test.Cardano.Ledger.Alonzo.Translation.TranslatableGen`).
      *
      * `slotToPOSIXTime` returns milliseconds, so `zeroTime` is the system start in ms and a
      * one-second slot is 1000 ms. NOTE: this is NOT `CardanoLedgerVectors.impSlotConfig` (which
      * has `zeroTime = 0`) - that one belongs to the STS Imp vectors in this same package. Using
      * the wrong one silently shifts every validity range.
      */
    val goldenSlotConfig: SlotConfig =
        SlotConfig(
          zeroTime = 1684445839000L * 1000L,
          zeroSlot = 0,
          slotLength = 1000,
          epochLength = 100,
          zeroEpoch = 0
        )

    /** One decoded corpus instance. The Tx and UTxO fields are ordinary Conway ledger CBOR; the
      * expected TxInfo uses cborg's generic `Serialise` encoding, kept as a [[Cbor.V]] tree.
      */
    case class Instance(
        index: Int,
        protocolMajor: Int,
        language: Int,
        utxoBytes: Array[Byte],
        txBytes: Array[Byte],
        expected: Cbor.V
    ) {
        def languageName: String = language match
            case PlutusV1 => "PlutusV1"
            case PlutusV2 => "PlutusV2"
            case PlutusV3 => "PlutusV3"
            case other    => s"Unknown($other)"

        override def toString: String = s"#$index PV$protocolMajor/$languageName"

        lazy val transaction: Transaction = Transaction.fromCbor(txBytes)

        lazy val utxo: Map[TransactionInput, TransactionOutput] = {
            import io.bullet.borer.Cbor as BorerCbor
            BorerCbor.decode(utxoBytes).to[Map[TransactionInput, TransactionOutput]].value
        }

        /** The payload of the `VersionedTxInfo` sum: `[conIdx, txInfoRecord]`. The constructor
          * index matches [[language]].
          */
        def txInfoRecord: Cbor.V = expected match
            case Cbor.Arr(items) if items.length == 2 =>
                val con = items(0).asLong.toInt
                require(
                  con == language,
                  s"VersionedTxInfo constructor $con does not match language $language"
                )
                items(1)
            case other =>
                throw new IllegalStateException(s"Unexpected VersionedTxInfo shape: $other")

        /** Field `i` of the expected TxInfo record. cborg encodes a constructor as
          * `listLen(1 + arity)` followed by the constructor index, so field `i` sits at `i + 1`.
          */
        def txInfoField(i: Int): Cbor.V = txInfoRecord match
            case Cbor.Arr(items) => items(i + 1)
            case other => throw new IllegalStateException(s"Expected TxInfo record, got: $other")
    }

    private val CorpusResource = "cardano-ledger-golden-translations.cbor.gz"

    private lazy val corpusBytes: Array[Byte] = {
        val stream = Option(getClass.getClassLoader.getResourceAsStream(CorpusResource)).getOrElse(
          throw new IllegalStateException(
            s"Golden translation corpus '$CorpusResource' is not on the test classpath."
          )
        )
        val bytes =
            try new GZIPInputStream(stream).readAllBytes()
            finally stream.close()
        val actual = MessageDigest
            .getInstance("SHA-256")
            .digest(bytes)
            .map(b => f"${b & 0xff}%02x")
            .mkString
        require(
          actual == CorpusSha256,
          s"""Golden corpus sha256 mismatch.
             |  expected $CorpusSha256
             |  actual   $actual
             |The vendored resource is not the pinned corpus. Re-diff it before trusting any
             |expectation this suite makes.""".stripMargin
        )
        bytes
    }

    /** All 100 instances, in file order. */
    lazy val instances: IndexedSeq[Instance] = {
        val b = corpusBytes
        val builder = IndexedSeq.newBuilder[Instance]
        // Top level is an indefinite-length array of instances.
        require(
          (b(0) & 0xff) == 0x9f,
          f"Expected a top-level indefinite array, got 0x${b(0) & 0xff}%02x"
        )
        var i = 1
        var n = 0
        while (b(i) & 0xff) != 0xff do {
            val (hdrMajor, hdrLen, _, afterHdr) = Cbor.header(b, i)
            require(
              hdrMajor == 4 && hdrLen == 5,
              s"Instance $n: expected a 5-field array, got major=$hdrMajor len=$hdrLen"
            )
            i = afterHdr
            val (protVer, i1) = Cbor.read(b, i)
            val (lang, i2) = Cbor.read(b, i1)
            val i3 = Cbor.skip(b, i2)
            val i4 = Cbor.skip(b, i3)
            val (expected, i5) = Cbor.read(b, i4)
            val protocolMajor = protVer match
                case Cbor.Arr(items) if items.nonEmpty => items(0).asLong.toInt
                case other => throw new IllegalStateException(s"Bad ProtVer: $other")
            builder += Instance(
              index = n,
              protocolMajor = protocolMajor,
              language = lang.asLong.toInt,
              utxoBytes = b.slice(i2, i3),
              txBytes = b.slice(i3, i4),
              expected = expected
            )
            i = i5
            n += 1
        }
        builder.result()
    }

    /** Minimal CBOR value reader.
      *
      * The expected-TxInfo field uses cborg's generic `Serialise` encoding, which borer has no
      * codec for, and we need byte offsets to slice the Tx and UTxO fields out verbatim. Both needs
      * are served by this reader; it is deliberately tiny and total over the subset the corpus
      * uses.
      *
      * cborg's conventions, verified against the corpus:
      *   - a constructor is `listLen(1 + arity)` then the constructor index, then the fields;
      *   - Haskell lists are indefinite-length arrays;
      *   - `Maybe` is `listLen 0` for `Nothing` and `listLen 1` for `Just x`;
      *   - newtypes (`Lovelace`, `TxId`, `Map`, ...) get the same `[0, payload]` treatment;
      *   - `AssocMap` is `[0, [[k, v], ...]]`, which preserves the ledger's key order.
      */
    object Cbor {
        sealed trait V {
            def asLong: Long = this match
                case UInt(v) => v
                case NInt(v) => v
                case other   => throw new IllegalStateException(s"Not an integer: $other")
            def asArray: IndexedSeq[V] = this match
                case Arr(items) => items
                case other      => throw new IllegalStateException(s"Not an array: $other")
            def asBytes: Array[Byte] = this match
                case Bytes(b) => b
                case other    => throw new IllegalStateException(s"Not a byte string: $other")
        }
        case class UInt(value: Long) extends V
        case class NInt(value: Long) extends V
        case class Bytes(value: Array[Byte]) extends V
        case class Text(value: String) extends V
        case class Arr(items: IndexedSeq[V]) extends V
        case class MapV(entries: IndexedSeq[(V, V)]) extends V
        case class Tagged(tag: Long, value: V) extends V
        case class Simple(value: Int) extends V

        /** Reads an item header: `(majorType, argument, indefinite, offsetAfterHeader)`. */
        def header(b: Array[Byte], i0: Int): (Int, Long, Boolean, Int) = {
            var i = i0
            val ib = b(i) & 0xff
            i += 1
            val major = ib >> 5
            val info = ib & 0x1f
            def take(n: Int): Long = {
                var v = 0L
                var k = 0
                while k < n do { v = (v << 8) | (b(i + k) & 0xffL); k += 1 }
                i += n
                v
            }
            info match
                case n if n < 24 => (major, n.toLong, false, i)
                case 24          => (major, take(1), false, i)
                case 25          => (major, take(2), false, i)
                case 26          => (major, take(4), false, i)
                case 27          => (major, take(8), false, i)
                case 31          => (major, 0L, true, i)
                case other =>
                    throw new IllegalStateException(s"Reserved additional info $other at $i0")
        }

        /** Reads one item, returning it and the offset just past it. */
        def read(b: Array[Byte], i0: Int): (V, Int) = {
            val (major, arg, indef, start) = header(b, i0)
            var i = start
            major match
                case 0 => (UInt(arg), i)
                case 1 => (NInt(-1L - arg), i)
                case 2 =>
                    if indef then {
                        val out = Array.newBuilder[Byte]
                        while (b(i) & 0xff) != 0xff do {
                            val (chunk, next) = read(b, i)
                            out ++= chunk.asBytes
                            i = next
                        }
                        (Bytes(out.result()), i + 1)
                    } else (Bytes(b.slice(i, i + arg.toInt)), i + arg.toInt)
                case 3 =>
                    // Indefinite-length text is a chunk sequence terminated by 0xff, exactly like
                    // indefinite bytes above. Without this branch the reader would return an
                    // empty Text and leave the offset before the first chunk, desynchronising
                    // every following item instead of failing - and `skip` already handles it,
                    // so the two would disagree on the same input.
                    if indef then {
                        val out = new StringBuilder
                        while (b(i) & 0xff) != 0xff do {
                            val (chunk, next) = read(b, i)
                            out ++= (chunk match
                                case Text(t) => t
                                case other =>
                                    throw new IllegalStateException(s"bad text chunk: $other"))
                            i = next
                        }
                        (Text(out.result()), i + 1)
                    } else {
                        val end = i + arg.toInt
                        (Text(new String(b.slice(i, end), "UTF-8")), end)
                    }
                case 4 =>
                    val out = IndexedSeq.newBuilder[V]
                    if indef then {
                        while (b(i) & 0xff) != 0xff do {
                            val (v, next) = read(b, i)
                            out += v
                            i = next
                        }
                        i += 1
                    } else {
                        var k = 0L
                        while k < arg do {
                            val (v, next) = read(b, i)
                            out += v
                            i = next
                            k += 1
                        }
                    }
                    (Arr(out.result()), i)
                case 5 =>
                    val out = IndexedSeq.newBuilder[(V, V)]
                    def pair(): Unit = {
                        val (k, i1) = read(b, i)
                        val (v, i2) = read(b, i1)
                        out += (k -> v)
                        i = i2
                    }
                    if indef then {
                        while (b(i) & 0xff) != 0xff do pair()
                        i += 1
                    } else {
                        var k = 0L
                        while k < arg do { pair(); k += 1 }
                    }
                    (MapV(out.result()), i)
                case 6 =>
                    val (v, next) = read(b, i)
                    (Tagged(arg, v), next)
                case 7     => (Simple(arg.toInt), i)
                case other => throw new IllegalStateException(s"Bad major type $other at $i0")
        }

        /** Returns the offset just past the item starting at `i0`, without building a value. */
        def skip(b: Array[Byte], i0: Int): Int = {
            val (major, arg, indef, start) = header(b, i0)
            var i = start
            major match
                case 0 | 1 | 7 => i
                case 2 | 3 =>
                    if indef then {
                        while (b(i) & 0xff) != 0xff do i = skip(b, i)
                        i + 1
                    } else i + arg.toInt
                case 4 =>
                    if indef then {
                        while (b(i) & 0xff) != 0xff do i = skip(b, i)
                        i + 1
                    } else {
                        var k = 0L
                        while k < arg do { i = skip(b, i); k += 1 }
                        i
                    }
                case 5 =>
                    if indef then {
                        while (b(i) & 0xff) != 0xff do { i = skip(b, i); i = skip(b, i) }
                        i + 1
                    } else {
                        var k = 0L
                        while k < arg do { i = skip(b, i); i = skip(b, i); k += 1 }
                        i
                    }
                case 6     => skip(b, i)
                case other => throw new IllegalStateException(s"Bad major type $other at $i0")
        }
    }
}
